const translations = {
  uz: {
    mHome: "Bosh sahifa",
    mPlay: "O'yin",
    mPuzzles: "Boshqotirmalar",
    mLeaderboard: "Reyting",
    mHistory: "O'yinlar tarixi",
    loginText: "Kirish",
    profileText: "Profil",
    dashWelcomeTitle: "Xush kelibsiz, Shaxmat ixlosmandi!",
    dashDesc: "Professional darajada shaxmat o'ynang, statistikalaringizni kuzating va o'z reytingingizni oshiring.",
    dashStartBtn: "O'yinni boshlash",
    dashDailyTitle: "Kunlik Boshqotirma",
    dashDailyDesc: "Har kuni yangi taktik topishmoqlar yeching va mahoratingizni oshiring.",
    streakText: "Kunlik ketma-ketlik",
    panelStatsHeader: "Statistika",
    labelWhiteWins: "Oq g'alaba:",
    labelBlackWins: "Qora g'alaba:",
    labelDraws: "Durrang:",
    btnResetStats: "Tozalash",
    btnNewGame: "Yangi 🔄",
    btnResign: "Taslim 🏳️",
    panelHistoryHeader: "Tarix",
    whiteText: "Oq",
    blackText: "Qora",
    whiteTimeUp: "Oqning vaqti tugadi! Qora g'alaba.",
    blackTimeUp: "Qoraning vaqti tugadi! Oq g'alaba.",
    whiteResigned: "Oq taslim bo'ldi!",
    blackResigned: "Qora taslim bo'ldi!",
    drawConfirm: "Durrang taklifiga rozi bo'lasizmi?",
    drawAlert: "O'yin durrang!",
    leaderboardSoon: "Reyting sahifasi tez kunda!",
    loginCardTitle: "Tizimga kirish",
    labelLoginUsername: "Foydalanuvchi nomi",
    labelLoginPassword: "Parol",
    btnLoginSubmit: "Kirish",
    noAccountText: "Hisobingiz yo'qmi?",
    goToRegisterLink: "Ro'yxatdan o'tish",
    regCardTitle: "Ro'yxatdan o'tish",
    labelRegUsername: "Foydalanuvchi nomi",
    labelRegEmail: "Pochta",
    labelRegPassword: "Parol",
    btnRegSubmit: "Ro'yxatdan o'tish",
    hasAccountText: "Hisobingiz bormi?",
    goToLoginLink: "Kirish",
    profileCardTitle: "Shaxsiy Profil",
    profLabelWins: "Oq g'alaba:",
    profLabelLosses: "Qora g'alaba:",
    profLabelDraws: "Durrang:",
    profLabelRating: "Reyting:",
    btnLogout: "Hisobdan chiqish",
    fillAllFields: "Barcha maydonlarni to'ldiring!",
    userExists: "Bu nomli foydalanuvchi mavjud!",
    wrongCredentials: "Ism yoki parol xato!",
    regSuccess: "Muvaffaqiyatli ro'yxatdan o'tdingiz!",
    leaderboardTitle: "O'yinchilar Reytingi",
    leaderboardDesc: "Ro'yxatdagi barcha o'yinchilarning g'alabalari bo'yicha umumiy jadvali",
    historyTitle: "O'yinlar tarixi",
    historyDesc: "Sizning oxirgi o'ynagan o'yinlaringiz ro'yxati",
    dashPlayerTitle: "Top 5 G'oliblar",
    dashPlayerDesc: "Eng ko'p g'alaba qozongan chempionlar.",
    onlineMode: "Online rejim",
    localMode: "Lokal rejim",
    createRoom: "Xona yaratish",
    joinRoom: "Xonaga qo'shilish",
    roomCode: "Xona kodi",
    enterRoomCode: "Xona kodini kiriting",
    playWithFriend: "Do'stga qarshi o'ynash",
    peerId: "Mening ID:",
    connectPeer: "Do'stga ulanish",
    friendPeerId: "Do'stingiz ID si",
    drawOffer: "Durrang taklifi",
    drawOffered: "Raqib sizga durrang taklif qildi!",
    drawAccepted: "Durrang qabul qilindi!",
    drawDeclined: "Durrang rad etildi!",
    pgnExport: "PGN eksport",
    pgnDownloaded: "PGN fayli yuklandi!",
    tournamentsTitle: "Turnirlar",
    tournamentsDesc: "Faol turnirlar va musobaqalar",
    btnCreateTournament: "+ Yanga Turnir Yaratish",
    friendsTitle: "Do'stlar",
    friendsDesc: "Do'stlar ro'yxati va so'rovlar",
    btnSendFriendRequest: "Do'stlik so'rash",
    btnViewRequests: "So'rovlar",
    clubsTitle: "Klublar",
    clubsDesc: "Shaxmat klublari va hamjamiyatlar",
    btnCreateClub: "+ Yanga Klub Yaratish",
    chatTitle: "Chat",
    chatDesc: "Xabarlar va suhbatlar",
    btnSendChatMessage: "Yuborish",
    mChat: "Chat",
  },
  en: {
    mHome: "Home",
    mPlay: "Play",
    mPuzzles: "Puzzles",
    mLeaderboard: "Leaderboard",
    mHistory: "Game History",
    loginText: "Login",
    profileText: "Profile",
    dashWelcomeTitle: "Welcome, Chess Enthusiast!",
    dashDesc: "Play professional chess, track your stats, and boost your rating.",
    dashStartBtn: "Start Playing",
    dashDailyTitle: "Daily Puzzle",
    dashDailyDesc: "Solve new tactical puzzles every day to improve your skills.",
    streakText: "Days Streak",
    panelStatsHeader: "Statistics",
    labelWhiteWins: "White Wins:",
    labelBlackWins: "Black Wins:",
    labelDraws: "Draws:",
    btnResetStats: "Reset",
    btnNewGame: "New 🔄",
    btnResign: "Resign 🏳️",
    panelHistoryHeader: "History",
    whiteText: "White",
    blackText: "Black",
    whiteTimeUp: "White's time is up! Black wins.",
    blackTimeUp: "Black's time is up! White wins.",
    whiteResigned: "White resigned!",
    blackResigned: "Black resigned!",
    drawConfirm: "Agree to a draw?",
    drawAlert: "Game drawn!",
    leaderboardSoon: "Leaderboard coming soon!",
    loginCardTitle: "Login",
    labelLoginUsername: "Username",
    labelLoginPassword: "Password",
    btnLoginSubmit: "Login",
    noAccountText: "Don't have an account?",
    goToRegisterLink: "Register",
    regCardTitle: "Register",
    labelRegUsername: "Username",
    labelRegEmail: "Email",
    labelRegPassword: "Password",
    btnRegSubmit: "Register",
    hasAccountText: "Already have an account?",
    goToLoginLink: "Login",
    profileCardTitle: "User Profile",
    profLabelWins: "White Wins:",
    profLabelLosses: "Black Wins:",
    profLabelDraws: "Draws:",
    profLabelRating: "Rating:",
    btnLogout: "Logout",
    fillAllFields: "Please fill in all fields!",
    userExists: "User already exists!",
    wrongCredentials: "Incorrect details!",
    regSuccess: "Successfully registered!",
    leaderboardTitle: "Players Leaderboard",
    leaderboardDesc: "Complete ranking of all players by wins",
    historyTitle: "Game History",
    historyDesc: "List of your recent games",
    dashPlayerTitle: "Top 5 Winners",
    dashPlayerDesc: "Champions with the most wins.",
    onlineMode: "Online mode",
    localMode: "Local mode",
    createRoom: "Create Room",
    joinRoom: "Join Room",
    roomCode: "Room code",
    enterRoomCode: "Enter room code",
    playWithFriend: "Play with Friend",
    peerId: "My ID:",
    connectPeer: "Connect to Friend",
    friendPeerId: "Friend's Peer ID",
    drawOffer: "Draw offer",
    drawOffered: "Opponent offered a draw!",
    drawAccepted: "Draw accepted!",
    drawDeclined: "Draw declined!",
    pgnExport: "PGN Export",
    pgnDownloaded: "PGN file downloaded!",
    tournamentsTitle: "Tournaments",
    tournamentsDesc: "Active tournaments and competitions",
    btnCreateTournament: "+ Create Tournament",
    friendsTitle: "Friends",
    friendsDesc: "Friends list and requests",
    btnSendFriendRequest: "Send Request",
    btnViewRequests: "Requests",
    clubsTitle: "Clubs",
    clubsDesc: "Chess clubs and communities",
    btnCreateClub: "+ Create Club",
    chatTitle: "Chat",
    chatDesc: "Messages and conversations",
    btnSendChatMessage: "Send",
    mChat: "Chat",
  },
  ru: {
    mHome: "Главная",
    mPlay: "Играть",
    mPuzzles: "Головоломки",
    mLeaderboard: "Рейтинг",
    mHistory: "История игр",
    loginText: "Войти",
    profileText: "Профиль",
    dashWelcomeTitle: "Добро пожаловать, любитель шахмат!",
    dashDesc: "Играйте в шахматы, отслеживайте статистику и повышайте свой рейтинг.",
    dashStartBtn: "Начать игру",
    dashDailyTitle: "Ежедневная задача",
    dashDailyDesc: "Решайте тактические задачи каждый день.",
    streakText: "Дней подряд",
    panelStatsHeader: "Статистика",
    labelWhiteWins: "Победы белых:",
    labelBlackWins: "Победы черных:",
    labelDraws: "Ничьи:",
    btnResetStats: "Сброс",
    btnNewGame: "Новая 🔄",
    btnResign: "Сдаться 🏳️",
    panelHistoryHeader: "История",
    whiteText: "Белые",
    blackText: "Черные",
    whiteTimeUp: "Время белых истекло!",
    blackTimeUp: "Время черных истекло!",
    whiteResigned: "Белые сдались!",
    blackResigned: "Черные сдались!",
    drawConfirm: "Согласны на ничью?",
    drawAlert: "Ничья!",
    leaderboardSoon: "Таблица лидеров скоро появится!",
    loginCardTitle: "Вход",
    labelLoginUsername: "Имя пользователя",
    labelLoginPassword: "Пароль",
    btnLoginSubmit: "Войти",
    noAccountText: "Нет аккаунта?",
    goToRegisterLink: "Регистрация",
    regCardTitle: "Регистрация",
    labelRegUsername: "Имя пользователя",
    labelRegEmail: "Почта",
    labelRegPassword: "Пароль",
    btnRegSubmit: "Зарегистрироваться",
    hasAccountText: "Уже есть аккаунт?",
    goToLoginLink: "Войти",
    profileCardTitle: "Профиль",
    profLabelWins: "Победы белых:",
    profLabelLosses: "Победы черных:",
    profLabelDraws: "Ничьи:",
    profLabelRating: "Рейтинг:",
    btnLogout: "Выйти",
    fillAllFields: "Заполните все поля!",
    userExists: "Пользователь уже существует!",
    wrongCredentials: "Неверные данные!",
    regSuccess: "Успешная регистрация!",
    leaderboardTitle: "Рейтинг игроков",
    leaderboardDesc: "Полный рейтинг всех игроков по победам",
    historyTitle: "История игр",
    historyDesc: "Список ваших последних игр",
    dashPlayerTitle: "Топ 5 победителей",
    dashPlayerDesc: "Чемпионы с наибольшим количеством побед.",
    onlineMode: "Онлайн режим",
    localMode: "Локальный режим",
    createRoom: "Создать комнату",
    joinRoom: "Присоединиться",
    roomCode: "Код комнаты",
    enterRoomCode: "Введите код комнаты",
    playWithFriend: "Играть с другом",
    peerId: "Мой ID:",
    connectPeer: "Подключиться к другу",
    friendPeerId: "Peer ID друга",
    drawOffer: "Предложение ничьей",
    drawOffered: "Соперник предложил ничью!",
    drawAccepted: "Ничья принята!",
    drawDeclined: "Ничья отклонена!",
    pgnExport: "PGN экспорт",
    pgnDownloaded: "PGN файл загружен!",
    tournamentsTitle: "Турниры",
    tournamentsDesc: "Активные турниры и соревнования",
    btnCreateTournament: "+ Создать турнир",
    friendsTitle: "Друзья",
    friendsDesc: "Список друзей и запросы",
    btnSendFriendRequest: "Отправить запрос",
    btnViewRequests: "Запросы",
    clubsTitle: "Клубы",
    clubsDesc: "Шахматные клубы и сообщества",
    btnCreateClub: "+ Создать клуб",
    chatTitle: "Чат",
    chatDesc: "Сообщения и разговоры",
    btnSendChatMessage: "Отправить",
    mChat: "Чат",
  },
  es: {
    mHome: "Inicio",
    mPlay: "Jugar",
    mPuzzles: "Puzzles",
    mLeaderboard: "Clasificación",
    mHistory: "Historial",
    loginText: "Entrar",
    profileText: "Perfil",
    dashWelcomeTitle: "¡Bienvenido, entusiasta del ajedrez!",
    dashDesc: "Juega al ajedrez profesional, sigue tus estadísticas y mejora tu clasificación.",
    dashStartBtn: "Empezar a jugar",
    dashDailyTitle: "Puzzle diario",
    dashDailyDesc: "Resuelve nuevos puzzles tácticos cada día.",
    streakText: "Días seguidos",
    panelStatsHeader: "Estadísticas",
    labelWhiteWins: "Victorias blancas:",
    labelBlackWins: "Victorias negras:",
    labelDraws: "Empates:",
    btnResetStats: "Borrar",
    btnNewGame: "Nueva 🔄",
    btnResign: "Rendirse 🏳️",
    panelHistoryHeader: "Historial",
    whiteText: "Blancas",
    blackText: "Negras",
    whiteTimeUp: "¡Se acabó el tiempo de blancas!",
    blackTimeUp: "¡Se acabó el tiempo de negras!",
    whiteResigned: "¡Blancas se rindieron!",
    blackResigned: "¡Negras se rindieron!",
    drawConfirm: "¿Aceptas el empate?",
    drawAlert: "¡Empate!",
    leaderboardSoon: "¡Clasificación próximamente!",
    loginCardTitle: "Iniciar sesión",
    labelLoginUsername: "Usuario",
    labelLoginPassword: "Contraseña",
    btnLoginSubmit: "Entrar",
    noAccountText: "¿No tienes cuenta?",
    goToRegisterLink: "Registrarse",
    regCardTitle: "Registro",
    labelRegUsername: "Usuario",
    labelRegEmail: "Correo",
    labelRegPassword: "Contraseña",
    btnRegSubmit: "Registrarse",
    hasAccountText: "¿Ya tienes cuenta?",
    goToLoginLink: "Entrar",
    profileCardTitle: "Perfil",
    profLabelWins: "Victorias blancas:",
    profLabelLosses: "Victorias negras:",
    profLabelDraws: "Empates:",
    profLabelRating: "Clasificación:",
    btnLogout: "Cerrar sesión",
    fillAllFields: "¡Rellena todos los campos!",
    userExists: "¡Usuario ya existe!",
    wrongCredentials: "¡Datos incorrectos!",
    regSuccess: "¡Registrado con éxito!",
    leaderboardTitle: "Clasificación de jugadores",
    leaderboardDesc: "Ranking completo de todos los jugadores por victorias",
    historyTitle: "Historial de partidas",
    historyDesc: "Lista de tus partidas recientes",
    dashPlayerTitle: "Top 5 Ganadores",
    dashPlayerDesc: "Campeones con más victorias.",
    onlineMode: "Modo online",
    localMode: "Modo local",
    createRoom: "Crear sala",
    joinRoom: "Unirse",
    roomCode: "Código de sala",
    enterRoomCode: "Ingresa el código",
    playWithFriend: "Jugar con amigo",
    peerId: "Mi ID:",
    connectPeer: "Conectar con amigo",
    friendPeerId: "Peer ID del amigo",
    drawOffer: "Ofrecer empate",
    drawOffered: "¡El oponente ofreció empate!",
    drawAccepted: "¡Empate aceptado!",
    drawDeclined: "¡Empate rechazado!",
    pgnExport: "Exportar PGN",
    pgnDownloaded: "¡Archivo PGN descargado!",
    tournamentsTitle: "Torneos",
    tournamentsDesc: "Torneos y competiciones activas",
    btnCreateTournament: "+ Crear Torneo",
    friendsTitle: "Amigos",
    friendsDesc: "Lista de amigos y solicitudes",
    btnSendFriendRequest: "Enviar solicitud",
    btnViewRequests: "Solicitudes",
    clubsTitle: "Clubes",
    clubsDesc: "Clubes de ajedrez y comunidades",
    btnCreateClub: "+ Crear Club",
    chatTitle: "Chat",
    chatDesc: "Mensajes y conversaciones",
    btnSendChatMessage: "Enviar",
    mChat: "Chat",
  },
  de: {
    mHome: "Startseite",
    mPlay: "Spielen",
    mPuzzles: "Puzzles",
    mLeaderboard: "Rangliste",
    mHistory: "Verlauf",
    loginText: "Anmelden",
    profileText: "Profil",
    dashWelcomeTitle: "Willkommen, Schachliebhaber!",
    dashDesc: "Spiele professionelles Schach, verfolge deine Statistiken und steigere deine Bewertung.",
    dashStartBtn: "Spiel starten",
    dashDailyTitle: "Tägliches Puzzle",
    dashDailyDesc: "Löse täglich neue taktische Puzzles.",
    streakText: "Tage in Folge",
    panelStatsHeader: "Statistiken",
    labelWhiteWins: "Weiße Siege:",
    labelBlackWins: "Schwarze Siege:",
    labelDraws: "Unentschieden:",
    btnResetStats: "Zurücksetzen",
    btnNewGame: "Neu 🔄",
    btnResign: "Aufgeben 🏳️",
    panelHistoryHeader: "Verlauf",
    whiteText: "Weiß",
    blackText: "Schwarz",
    whiteTimeUp: "Weiß Zeit abgelaufen!",
    blackTimeUp: "Schwarz Zeit abgelaufen!",
    whiteResigned: "Weiß hat aufgegeben!",
    blackResigned: "Schwarz hat aufgegeben!",
    drawConfirm: "Unentschieden annehmen?",
    drawAlert: "Unentschieden!",
    leaderboardSoon: "Rangliste demnächst!",
    loginCardTitle: "Anmelden",
    labelLoginUsername: "Benutzername",
    labelLoginPassword: "Passwort",
    btnLoginSubmit: "Anmelden",
    noAccountText: "Kein Konto?",
    goToRegisterLink: "Registrieren",
    regCardTitle: "Registrierung",
    labelRegUsername: "Benutzername",
    labelRegEmail: "E-Mail",
    labelRegPassword: "Passwort",
    btnRegSubmit: "Registrieren",
    hasAccountText: "Bereits ein Konto?",
    goToLoginLink: "Anmelden",
    profileCardTitle: "Profil",
    profLabelWins: "Weiße Siege:",
    profLabelLosses: "Schwarze Siege:",
    profLabelDraws: "Unentschieden:",
    profLabelRating: "Bewertung:",
    btnLogout: "Abmelden",
    fillAllFields: "Bitte alle Felder ausfüllen!",
    userExists: "Benutzer existiert bereits!",
    wrongCredentials: "Falsche Daten!",
    regSuccess: "Erfolgreich registriert!",
    leaderboardTitle: "Spieler-Rangliste",
    leaderboardDesc: "Vollständige Rangliste aller Spieler nach Siegen",
    historyTitle: "Spielverlauf",
    historyDesc: "Liste deiner letzten Spiele",
    dashPlayerTitle: "Top 5 Gewinner",
    dashPlayerDesc: "Meiste Siege.",
    onlineMode: "Online-Modus",
    localMode: "Lokal-Modus",
    createRoom: "Raum erstellen",
    joinRoom: "Beitreten",
    roomCode: "Raumcode",
    enterRoomCode: "Raumcode eingeben",
    playWithFriend: "Mit Freund spielen",
    peerId: "Meine ID:",
    connectPeer: "Mit Freund verbinden",
    friendPeerId: "Peer-ID des Freundes",
    drawOffer: "Unentschieden anbieten",
    drawOffered: "Gegner bietet Unentschieden an!",
    drawAccepted: "Unentschieden angenommen!",
    drawDeclined: "Unentschieden abgelehnt!",
    pgnExport: "PGN Export",
    pgnDownloaded: "PGN Datei heruntergeladen!",
    tournamentsTitle: "Turniere",
    tournamentsDesc: "Aktive Turniere und Wettbewerbe",
    btnCreateTournament: "+ Turnier erstellen",
    friendsTitle: "Freunde",
    friendsDesc: "Freundesliste und Anfragen",
    btnSendFriendRequest: "Anfrage senden",
    btnViewRequests: "Anfragen",
    clubsTitle: "Clubs",
    clubsDesc: "Schachclubs und Gemeinschaften",
    btnCreateClub: "+ Club erstellen",
    chatTitle: "Chat",
    chatDesc: "Nachrichten und Gespräche",
    btnSendChatMessage: "Senden",
    mChat: "Chat",
  },
  fr: {
    mHome: "Accueil",
    mPlay: "Jouer",
    mPuzzles: "Puzzles",
    mLeaderboard: "Classement",
    mHistory: "Historique",
    loginText: "Connexion",
    profileText: "Profil",
    dashWelcomeTitle: "Bienvenue, amateur d'échecs!",
    dashDesc: "Jouez aux échecs professionnels, suivez vos statistiques et améliorez votre classement.",
    dashStartBtn: "Commencer à jouer",
    dashDailyTitle: "Puzzle quotidien",
    dashDailyDesc: "Résolvez de nouveaux puzzles tactiques chaque jour.",
    streakText: "Jours consécutifs",
    panelStatsHeader: "Statistiques",
    labelWhiteWins: "Victoires blancs:",
    labelBlackWins: "Victoires noirs:",
    labelDraws: "Nuls:",
    btnResetStats: "Réinitialiser",
    btnNewGame: "Nouveau 🔄",
    btnResign: "Abandonner 🏳️",
    panelHistoryHeader: "Historique",
    whiteText: "Blancs",
    blackText: "Noirs",
    whiteTimeUp: "Temps des blancs écoulé!",
    blackTimeUp: "Temps des noirs écoulé!",
    whiteResigned: "Blancs ont abandonné!",
    blackResigned: "Noirs ont abandonné!",
    drawConfirm: "Accepter le match nul?",
    drawAlert: "Match nul!",
    leaderboardSoon: "Classement bientôt!",
    loginCardTitle: "Connexion",
    labelLoginUsername: "Nom d'utilisateur",
    labelLoginPassword: "Mot de passe",
    btnLoginSubmit: "Connexion",
    noAccountText: "Pas de compte?",
    goToRegisterLink: "S'inscrire",
    regCardTitle: "Inscription",
    labelRegUsername: "Nom d'utilisateur",
    labelRegEmail: "Email",
    labelRegPassword: "Mot de passe",
    btnRegSubmit: "S'inscrire",
    hasAccountText: "Vous avez déjà un compte?",
    goToLoginLink: "Connexion",
    profileCardTitle: "Profil",
    profLabelWins: "Victoires blancs:",
    profLabelLosses: "Victoires noirs:",
    profLabelDraws: "Nuls:",
    profLabelRating: "Classement:",
    btnLogout: "Déconnexion",
    fillAllFields: "Remplissez tous les champs!",
    userExists: "Utilisateur existe déjà!",
    wrongCredentials: "Données incorrectes!",
    regSuccess: "Inscription réussie!",
    leaderboardTitle: "Classement des joueurs",
    leaderboardDesc: "Classement complet de tous les joueurs par victoires",
    historyTitle: "Historique des parties",
    historyDesc: "Liste de vos parties récentes",
    dashPlayerTitle: "Top 5 Gagnants",
    dashPlayerDesc: "Champions avec le plus de victoires.",
    onlineMode: "Mode en ligne",
    localMode: "Mode local",
    createRoom: "Créer une salle",
    joinRoom: "Rejoindre",
    roomCode: "Code de salle",
    enterRoomCode: "Entrez le code",
    playWithFriend: "Jouer avec un ami",
    peerId: "Mon ID:",
    connectPeer: "Se connecter à un ami",
    friendPeerId: "Peer ID de l'ami",
    drawOffer: "Offrir match nul",
    drawOffered: "L'adversaire propose un match nul!",
    drawAccepted: "Match nul accepté!",
    drawDeclined: "Match nul refusé!",
    pgnExport: "Exporter PGN",
    pgnDownloaded: "Fichier PGN téléchargé!",
    tournamentsTitle: "Tournois",
    tournamentsDesc: "Tournois et compétitions actifs",
    btnCreateTournament: "+ Créer un tournoi",
    friendsTitle: "Amis",
    friendsDesc: "Liste d'amis et demandes",
    btnSendFriendRequest: "Envoyer demande",
    btnViewRequests: "Demandes",
    clubsTitle: "Clubs",
    clubsDesc: "Clubs d'échecs et communautés",
    btnCreateClub: "+ Créer un club",
    chatTitle: "Chat",
    chatDesc: "Messages et conversations",
    btnSendChatMessage: "Envoyer",
    mChat: "Chat",
  }
};

i18next.init({
  lng: localStorage.getItem("justChessLang") || "uz",
  debug: false,
  resources: {
    uz: { translation: translations.uz },
    en: { translation: translations.en },
    ru: { translation: translations.ru },
    es: { translation: translations.es },
    de: { translation: translations.de },
    fr: { translation: translations.fr }
  }
}, function(err, t) {
  if (!err) updateUI();
});

function leaderboardAlertText() {
  return i18next.t('leaderboardSoon');
}

function updateUI() {
  const t = (key) => i18next.t(key);
  
  const mHome = document.getElementById("mHome"); if (mHome) mHome.textContent = t('mHome');
  const mPlay = document.getElementById("mPlay"); if (mPlay) mPlay.textContent = t('mPlay');
  const mLeaderboard = document.getElementById("mLeaderboard"); if (mLeaderboard) mLeaderboard.textContent = t('mLeaderboard');
  const mHistory = document.getElementById("mHistory"); if (mHistory) mHistory.textContent = t('mHistory');
  const mTournaments = document.getElementById("mTournaments"); if (mTournaments) mTournaments.textContent = t('tournamentsTitle');
  const mClubs = document.getElementById("mClubs"); if (mClubs) mClubs.textContent = t('clubsTitle');
  
  const dashWelcomeTitle = document.getElementById("dashWelcomeTitle"); if (dashWelcomeTitle) dashWelcomeTitle.textContent = t('dashWelcomeTitle');
  const dashDesc = document.getElementById("dashDesc"); if (dashDesc) dashDesc.textContent = t('dashDesc');
  const dashStartBtn = document.getElementById("dashStartBtn"); if (dashStartBtn) dashStartBtn.textContent = t('dashStartBtn');
  const dashDailyTitle = document.getElementById("dashDailyTitle"); if (dashDailyTitle) dashDailyTitle.textContent = t('dashDailyTitle');
  const dashDailyDesc = document.getElementById("dashDailyDesc"); if (dashDailyDesc) dashDailyDesc.textContent = t('dashDailyDesc');
  const dashPlayerTitle = document.getElementById("dashPlayerTitle"); if (dashPlayerTitle) dashPlayerTitle.textContent = t('dashPlayerTitle');
  const dashPlayerDesc = document.getElementById("dashPlayerDesc"); if (dashPlayerDesc) dashPlayerDesc.textContent = t('dashPlayerDesc');
  
  const panelStatsHeader = document.getElementById("panelStatsHeader"); if (panelStatsHeader) panelStatsHeader.textContent = t('panelStatsHeader');
  const labelWhiteWins = document.getElementById("labelWhiteWins"); if (labelWhiteWins) labelWhiteWins.textContent = t('labelWhiteWins');
  const labelBlackWins = document.getElementById("labelBlackWins"); if (labelBlackWins) labelBlackWins.textContent = t('labelBlackWins');
  const labelDraws = document.getElementById("labelDraws"); if (labelDraws) labelDraws.textContent = t('labelDraws');
  const btnResetStats = document.getElementById("btnResetStats"); if (btnResetStats) btnResetStats.textContent = t('btnResetStats');
  const btnNewGame = document.getElementById("btnNewGame"); if (btnNewGame) btnNewGame.textContent = t('btnNewGame');
  const btnResign = document.getElementById("btnResign"); if (btnResign) btnResign.textContent = t('btnResign');
  const panelHistoryHeader = document.getElementById("panelHistoryHeader"); if (panelHistoryHeader) panelHistoryHeader.textContent = t('panelHistoryHeader');
  
  const loginCardTitle = document.getElementById("loginCardTitle"); if (loginCardTitle) loginCardTitle.textContent = t('loginCardTitle');
  const labelLoginUsername = document.getElementById("labelLoginUsername"); if (labelLoginUsername) labelLoginUsername.textContent = t('labelLoginUsername');
  const labelLoginPassword = document.getElementById("labelLoginPassword"); if (labelLoginPassword) labelLoginPassword.textContent = t('labelLoginPassword');
  const btnLoginSubmit = document.getElementById("btnLoginSubmit"); if (btnLoginSubmit) btnLoginSubmit.textContent = t('btnLoginSubmit');
  const noAccountText = document.getElementById("noAccountText"); if (noAccountText) noAccountText.textContent = t('noAccountText');
  const goToRegisterLink = document.getElementById("goToRegisterLink"); if (goToRegisterLink) goToRegisterLink.textContent = t('goToRegisterLink');

  const regCardTitle = document.getElementById("regCardTitle"); if (regCardTitle) regCardTitle.textContent = t('regCardTitle');
  const labelRegUsername = document.getElementById("labelRegUsername"); if (labelRegUsername) labelRegUsername.textContent = t('labelRegUsername');
  const labelRegEmail = document.getElementById("labelRegEmail"); if (labelRegEmail) labelRegEmail.textContent = t('labelRegEmail');
  const labelRegPassword = document.getElementById("labelRegPassword"); if (labelRegPassword) labelRegPassword.textContent = t('labelRegPassword');
  const btnRegSubmit = document.getElementById("btnRegSubmit"); if (btnRegSubmit) btnRegSubmit.textContent = t('btnRegSubmit');
  const hasAccountText = document.getElementById("hasAccountText"); if (hasAccountText) hasAccountText.textContent = t('hasAccountText');
  const goToLoginLink = document.getElementById("goToLoginLink"); if (goToLoginLink) goToLoginLink.textContent = t('goToLoginLink');
  
  const profileCardTitle = document.getElementById("profileCardTitle"); if (profileCardTitle) profileCardTitle.textContent = t('profileCardTitle');
  const profLabelWins = document.getElementById("profLabelWins"); if (profLabelWins) profLabelWins.textContent = t('profLabelWins');
  const profLabelLosses = document.getElementById("profLabelLosses"); if (profLabelLosses) profLabelLosses.textContent = t('profLabelLosses');
  const profLabelDraws = document.getElementById("profLabelDraws"); if (profLabelDraws) profLabelDraws.textContent = t('profLabelDraws');
  const profLabelRating = document.getElementById("profLabelRating"); if (profLabelRating) profLabelRating.textContent = t('profLabelRating');
  const btnLogout = document.getElementById("btnLogout"); if (btnLogout) btnLogout.textContent = t('btnLogout');

  const leaderboardCardTitle = document.getElementById("leaderboardCardTitle"); if (leaderboardCardTitle) leaderboardCardTitle.textContent = t('leaderboardTitle');
  const leaderboardDesc = document.getElementById("leaderboardDesc"); if (leaderboardDesc) leaderboardDesc.textContent = t('leaderboardDesc');
  const historyCardTitle = document.getElementById("historyCardTitle"); if (historyCardTitle) historyCardTitle.textContent = t('historyTitle');
  const historyDesc = document.getElementById("historyDesc"); if (historyDesc) historyDesc.textContent = t('historyDesc');
  
  const tournamentsCardTitle = document.getElementById("tournamentsCardTitle"); if (tournamentsCardTitle) tournamentsCardTitle.textContent = t('tournamentsTitle');
  const tournamentsDesc = document.getElementById("tournamentsDesc"); if (tournamentsDesc) tournamentsDesc.textContent = t('tournamentsDesc');
  const btnCreateTournament = document.getElementById("btnCreateTournament"); if (btnCreateTournament) btnCreateTournament.textContent = t('btnCreateTournament');
  
  const friendsCardTitle = document.getElementById("friendsCardTitle"); if (friendsCardTitle) friendsCardTitle.textContent = t('friendsTitle');
  const friendsDesc = document.getElementById("friendsDesc"); if (friendsDesc) friendsDesc.textContent = t('friendsDesc');
  const btnSendFriendRequest = document.getElementById("btnSendFriendRequest"); if (btnSendFriendRequest) btnSendFriendRequest.textContent = t('btnSendFriendRequest');
  const btnViewRequests = document.getElementById("btnViewRequests"); if (btnViewRequests) btnViewRequests.textContent = t('btnViewRequests');
  
  const clubsCardTitle = document.getElementById("clubsCardTitle"); if (clubsCardTitle) clubsCardTitle.textContent = t('clubsTitle');
  const clubsDesc = document.getElementById("clubsDesc"); if (clubsDesc) clubsDesc.textContent = t('clubsDesc');
  const btnCreateClub = document.getElementById("btnCreateClub"); if (btnCreateClub) btnCreateClub.textContent = t('btnCreateClub');
  
  const chatCardTitle = document.getElementById("chatCardTitle"); if (chatCardTitle) chatCardTitle.textContent = t('chatTitle');
  const chatDesc = document.getElementById("chatDesc"); if (chatDesc) chatDesc.textContent = t('chatDesc');
  const btnSendChatMessage = document.getElementById("btnSendChatMessage"); if (btnSendChatMessage) btnSendChatMessage.textContent = t('btnSendChatMessage');

  if (typeof window.updateAuthHeaderUI === 'function') window.updateAuthHeaderUI();
  if (typeof window.updateStreakUI === 'function') window.updateStreakUI();
  if (typeof window.updateTimersDisplay === 'function') window.updateTimersDisplay();
}

window.setLanguage = function(lang) {
  currentLang = lang;
  localStorage.setItem("justChessLang", lang);
  i18next.changeLanguage(lang, () => {
    updateUI();
  });
};

window.changeLanguage = function(lang) {
  window.setLanguage(lang);
};
