const translations = {
  uz: {
    mHome: "Bosh sahifa",
    mPlay: "O'yin",
    mLeaderboard: "Reyting",
    mHistory: "O'yinlar tarixi",
    loginText: "Kirish",
    profileText: "Profil",
    dashWelcomeTitle: "Xush kelibsiz, Shaxmat ixlosmandi!",
    dashDesc: "Professional darajada shaxmat o'ynang, statistikalaringizni kuzating va o'z reytingingizni oshiring.",
    dashStartBtn: "O'yinni boshlash",
    streakText: "Kunlik ketma-ketlik",
    panelStatsHeader: "Statistika",
    labelWhiteWins: "Oq g'alaba:",
    labelBlackWins: "Qora g'alaba:",
    labelDraws: "Durrang:",
    btnResetStats: "Tozalash",
    btnNewGame: "Yangi 🔄",
    btnResign: "Taslim 🏳️",
    panelHistoryHeader: "Tarix",
    whiteText: "Oq",
    blackText: "Qora",
    whiteTimeUp: "Oqning vaqti tugadi! Qora g'alaba.",
    blackTimeUp: "Qoraning vaqti tugadi! Oq g'alaba.",
    whiteResigned: "Oq taslim bo'ldi!",
    blackResigned: "Qora taslim bo'ldi!",
    drawConfirm: "Durrang taklifiga rozi bo'lasizmi?",
    drawAlert: "O'yin durrang!",
    leaderboardSoon: "Reyting sahifasi tez kunda!",
    loginCardTitle: "Tizimga kirish",
    labelLoginUsername: "Foydalanuvchi nomi",
    labelLoginPassword: "Parol",
    btnLoginSubmit: "Kirish",
    noAccountText: "Hisobingiz yo'qmi?",
    goToRegisterLink: "Ro'yxatdan o'tish",
    regCardTitle: "Ro'yxatdan o'tish",
    labelRegUsername: "Foydalanuvchi nomi",
    labelRegEmail: "Pochta",
    labelRegPassword: "Parol",
    btnRegSubmit: "Ro'yxatdan o'tish",
    hasAccountText: "Hisobingiz bormi?",
    goToLoginLink: "Kirish",
    profileCardTitle: "Shaxsiy Profil",
    profLabelWins: "Oq g'alaba:",
    profLabelLosses: "Qora g'alaba:",
    profLabelDraws: "Durrang:",
    profLabelRating: "Reyting:",
    btnLogout: "Hisobdan chiqish",
    profRatingsBtn: "Reytinglar",
    profEditBtn: "Tahrirlash",
    profSaveBtn: "Saqlash",
    profRapidRating: "RAPID REYTING",
    profBlitzRating: "BLITZ REYTING",
    profBulletRating: "BULLET REYTING",
    profBestOpening: "ENG KUCHLI DEBYUT",
    profClubLabel: "KLUB",
    profStatusLabel: "STATUS",
    profStatusActive: "Faol o'yinchi",
    profFideIdLabel: "FIDE ID",
    profGoalLabel: "Maqsad",
    profCopyLinkBtn: "Profil havolasini nusxalash",
    fillAllFields: "Barcha maydonlarni to'ldiring!",
    userExists: "Bu nomli foydalanuvchi mavjud!",
    wrongCredentials: "Ism yoki parol xato!",
    regSuccess: "Muvaffaqiyatli ro'yxatdan o'tdingiz!",
    leaderboardTitle: "O'yinchilar Reytingi",
    leaderboardDesc: "Ro'yxatdagi barcha o'yinchilarning g'alabalari bo'yicha umumiy jadvali",
    historyTitle: "O'yinlar tarixi",
    historyDesc: "Sizning oxirgi o'ynagan o'yinlaringiz ro'yxati",
    dashPlayerTitle: "Top 5 G'oliblar",
    dashPlayerDesc: "Eng ko'p g'alaba qozongan chempionlar.",
    onlineMode: "Online rejim",
    createRoom: "Xona yaratish",
    joinRoom: "Xonaga qo'shilish",
    roomCode: "Xona kodi",
    enterRoomCode: "Xona kodini kiriting",
    drawOffer: "Durrang taklifi",
    drawOffered: "Raqib sizga durrang taklif qildi!",
    drawAccepted: "Durrang qabul qilindi!",
    drawDeclined: "Durrang rad etildi!",
    pgnExport: "PGN eksport",
    pgnDownloaded: "PGN fayli yuklandi!",
    tournamentsTitle: "Turnirlar",
    tournamentsDesc: "24 soat davomida har soatda arena turnirlari",
    clubsTitle: "Klublar",
    clubsDesc: "Shaxmat klublari va hamjamiyatlar",
    btnCreateClub: "+ Yanga Klub Yaratish",
    chatTitle: "Chat",
    chatDesc: "Xabarlar va suhbatlar",
    btnSendChatMessage: "Yuborish",
    mChat: "Chat",
    playOnlineBtn: "Onlayn o'ynash",
    tabPlayers: "O'yinchilar",
    tabClubs: "Klublar",
    searchCountry: "Davlatni qidiring...",
    filterAll: "Barchasi",
    filterRapid: "Rapid",
    filterBlitz: "Blits",
    filterBullet: "Bullet",
    btnView: "Ko'rish",
    membersLabel: "a'zo",
    colUsername: "Foydalanuvchi",
    colRating: "Reyting",
    colWinPoints: "G'alaba ochkosi",
    colWins: "G'alabalar",
    colGames: "O'yinlar",
    colWinPercent: "G'alaba %",
    colPlayer: "O'yinchi",
    mLeagues: "Ligalar",
    mChampions: "Chempionlar",
    mSettings: "Sozlamalar",
    waitingSearching: "Raqib qidirilmoqda...",
    waitingPlease: "Iltimos, kuting",
    historyPanelHeader: "Yurishlar tarixi",
    ratedLabel: "Reytingli",
    ratedSublabel: "O'yin rejimi",
    btnDrawText: "Durrang",
    btnPgnText: "PGN",
    btnStartGameText: "O'yinni boshlash",
    timerLabelJudaTez: "Juda tez",
    timerLabelBlits: "Blits",
    timerLabelTezkor: "Tezkor",
    historyAllText: "Barchasi",
    historyWinsText: "G'alabalar",
    historyLossesText: "Mag'lubiyatlar",
    historyDrawsText: "Duranglar",
    colDate: "Sana",
    colOpponent: "Raqib",
    colMode: "Rejim",
    colTime: "Vaqt",
    colResult: "Natija",
    leaguesDesc: "Har oyda yangilanadigan kontinental musobaqalar",
    leagueAsia: "Osiyo Ligasi",
    leagueEurope: "Yevropa Ligasi",
    leagueAfrica: "Afrika Ligasi",
    leagueSouthAmerica: "Janubiy Amerika Ligasi",
    leagueNorthAmerica: "Shimoliy Amerika Ligasi",
    leagueOceania: "Okeaniya Ligasi",
    leagueCardTeams: "{count} jamoa • Round-Robin",
    leagueCardDesc: "Barcha jamoalar o'zaro o'ynaydi. Eng ko'p ochko to'plagan jamoa g'olib!",
    leaguePlayAlert: "{mode} - Liga • {count} ta jamoa istagona o'ynaydi!",
    leagueTableRank: "O'RIN",
    leagueTableTeam: "JAMOA",
    leagueStandingsTitle: "Turnir jadvali",
    championWinnerLabel: "G'olib: Jamoa nomi",
    championsTitle: "Chempionlar Ligasi",
    championsSubtitle: "6 ta mintaqaviy liganing g'oliblari bosh sovrin uchun kurashadi",
    tournamentFormatTitle: "Turnir formati (Round-Robin)",
    roundRobinRule1: "Har bir ligada mintaqasidagi barcha jamoalar Round-Robin tizimida o'ynaydi",
    roundRobinRule2: "Barcha jamoalar bir-biri bilan 1 marta o'ynaydi (jami 28 o'yin)",
    roundRobinRule3: "G'alaba: +3 ochko, Durang: +1 ochko, Mag'lubiyat: +0 ochko",
    roundRobinRule4: "Eng ko'p ochko to'plagan jamoa ligani chempioni bo'ladi",
    settingsTitle: "Sozlamalar",
    settingsSubtitle: "Sizning shaxsiy afzalliklaringiz",
    settingsCountryTitle: "🌍 Davlat bayrog'i",
    settingsCountryLabel: "Davlat kodi:",
    settingsLanguageTitle: "🗣️ Interfeys tili",
    settingsLanguageLabel: "Til:",
    settingsSoundTitle: "🔊 Ovoz",
    settingsSoundLabel: "Ovozli:",
    settingsVolumeLabel: "Volume:",
    settingsDesignTitle: "🎨 Dizayn",
    settingsThemeLabel: "Taxta mavsu:",
    settingsCoordsLabel: "Koordinatalar:",
    settingsSaveBtn: "Saqlash",
    settingsResetBtn: "Qayta o'rnatish",
    continentAll: "Barchasi",
    continentAsia: "Osiyo",
    continentEurope: "Yevropa",
    continentAfrica: "Afrika",
    continentSouthAmerica: "Janubiy Amerika",
    continentNorthAmerica: "Shimoliy Amerika",
    continentOceania: "Okeaniya",
    clubDetailBack: "Orqaga",
    clubDetailMembersCount: "a'zo",
    clubDetailEventsCount: "musobaqa",
    clubDetailMembersCard: "A'zolar",
    clubDetailEventsCard: "O'tkazilgan musobaqalar",
    clubDetailPointsCard: "Klub ballari",
    clubDetailAboutTitle: "Klub haqida",
    clubDetailAboutText: "Rasmiy {country} Shaxmat Klubiga xush kelibsiz! Biz mahoratimizni oshirish, turnirlar tashkil qilish va {country}da shaxmatni rivojlantirishga intilayotgan shaxmat ishqibozlari hamjamiyatimiz. Bizga qo'shiling — musobaqalashing, o'rganing va aloqada bo'ling!",
    clubDetailJoinBtn: "Klubga qo'shilish",
    clubDetailLeaveBtn: "Klubdan chiqish",
    clubDetailTournamentsBtn: "Turnirlar",
    clubDetailHistoryBtn: "Tarix",
    clubDetailAllClubsBtn: "Barcha klublar",
    clubDetailTopPlayersTitle: "Eng kuchli o'yinchilar",
    clubDetailNoMembers: "Hali a'zolar yo'q. Birinchi bo'lib qo'shiling!",
    loadingText: "Yuklanmoqda...",
    clubLeagueTitle: "{country} liga kalendari",
    clubLeagueDesc: "Ushbu klub ishtirok etadigan liga o'yinlari",
    clubLeagueRoundRobin: "Round-Robin • {count} jamoa",
    clubLeagueBadge: "Liga taqvimi",
    clubLeagueRound: "Bosqich",
    clubLeagueClub: "Klub",
    clubLeagueOpponent: "Raqib",
    clubLeagueVenue: "Maydon",
    clubLeagueDate: "Sana",
    clubLeagueTime: "Vaqt",
    clubLeagueHome: "O'z maydonida",
    clubLeagueAway: "Mehmonda",
    clubHistoryTitle: "{country} - A'zolar tarixi",
    clubHistoryDesc: "Klub a'zolari va ularning qo'shilgan sanalari",
    clubHistoryEmpty: "Hali klubga a'zolar yo'q",
    clubHistoryGamesCard: "O'yinlar",
    clubHistoryMembersList: "{count} ta a'zo (yangidan eskiyga)",
    clubHistoryJoined: "Qo'shilgan:",
    clubHistoryJoinUnknown: "Aniqlanmagan",
  },
  en: {
    mHome: "Home",
    mPlay: "Play",
    mLeaderboard: "Leaderboard",
    mHistory: "Game History",
    loginText: "Login",
    profileText: "Profile",
    dashWelcomeTitle: "Welcome, Chess Enthusiast!",
    dashDesc: "Play professional chess, track your stats, and boost your rating.",
    dashStartBtn: "Start Playing",
    streakText: "Days Streak",
    panelStatsHeader: "Statistics",
    labelWhiteWins: "White Wins:",
    labelBlackWins: "Black Wins:",
    labelDraws: "Draws:",
    btnResetStats: "Reset",
    btnNewGame: "New 🔄",
    btnResign: "Resign 🏳️",
    panelHistoryHeader: "History",
    whiteText: "White",
    blackText: "Black",
    whiteTimeUp: "White's time is up! Black wins.",
    blackTimeUp: "Black's time is up! White wins.",
    whiteResigned: "White resigned!",
    blackResigned: "Black resigned!",
    drawConfirm: "Agree to a draw?",
    drawAlert: "Game drawn!",
    leaderboardSoon: "Leaderboard coming soon!",
    loginCardTitle: "Login",
    labelLoginUsername: "Username",
    labelLoginPassword: "Password",
    btnLoginSubmit: "Login",
    noAccountText: "Don't have an account?",
    goToRegisterLink: "Register",
    regCardTitle: "Register",
    labelRegUsername: "Username",
    labelRegEmail: "Email",
    labelRegPassword: "Password",
    btnRegSubmit: "Register",
    hasAccountText: "Already have an account?",
    goToLoginLink: "Login",
    profileCardTitle: "User Profile",
    profLabelWins: "White Wins:",
    profLabelLosses: "Black Wins:",
    profLabelDraws: "Draws:",
    profLabelRating: "Rating:",
    btnLogout: "Logout",
    profRatingsBtn: "Ratings",
    profEditBtn: "Edit",
    profSaveBtn: "Save",
    profRapidRating: "RAPID RATING",
    profBlitzRating: "BLITZ RATING",
    profBulletRating: "BULLET RATING",
    profBestOpening: "BEST OPENING",
    profClubLabel: "CLUB",
    profStatusLabel: "STATUS",
    profStatusActive: "Active player",
    profFideIdLabel: "FIDE ID",
    profGoalLabel: "Goal",
    profCopyLinkBtn: "Copy profile link",
    fillAllFields: "Please fill in all fields!",
    userExists: "User already exists!",
    wrongCredentials: "Incorrect details!",
    regSuccess: "Successfully registered!",
    leaderboardTitle: "Players Leaderboard",
    leaderboardDesc: "Complete ranking of all players by wins",
    historyTitle: "Game History",
    historyDesc: "List of your recent games",
    dashPlayerTitle: "Top 5 Winners",
    dashPlayerDesc: "Champions with the most wins.",
    onlineMode: "Online mode",
    createRoom: "Create Room",
    joinRoom: "Join Room",
    roomCode: "Room code",
    enterRoomCode: "Enter room code",
    drawOffer: "Draw offer",
    drawOffered: "Opponent offered a draw!",
    drawAccepted: "Draw accepted!",
    drawDeclined: "Draw declined!",
    pgnExport: "PGN Export",
    pgnDownloaded: "PGN file downloaded!",
    tournamentsTitle: "Tournaments",
    tournamentsDesc: "Arena tournaments every hour for 24 hours",
    clubsTitle: "Clubs",
    clubsDesc: "Chess clubs and communities",
    btnCreateClub: "+ Create Club",
    chatTitle: "Chat",
    chatDesc: "Messages and conversations",
    btnSendChatMessage: "Send",
    mChat: "Chat",
    playOnlineBtn: "Play Online",
    tabPlayers: "Players",
    tabClubs: "Clubs",
    searchCountry: "Search for a country...",
    filterAll: "All",
    filterRapid: "Rapid",
    filterBlitz: "Blitz",
    filterBullet: "Bullet",
    btnView: "View",
    membersLabel: "members",
    colUsername: "Username",
    colRating: "Rating",
    colWinPoints: "Win Points",
    colWins: "Wins",
    colGames: "Games",
    colWinPercent: "Win %",
    colPlayer: "Player",
    mLeagues: "Leagues",
    mChampions: "Champions",
    mSettings: "Settings",
    waitingSearching: "Searching for opponent...",
    waitingPlease: "Please wait",
    historyPanelHeader: "Move History",
    ratedLabel: "Rated",
    ratedSublabel: "Game mode",
    btnDrawText: "Draw",
    btnPgnText: "PGN",
    btnStartGameText: "Start Game",
    timerLabelJudaTez: "Bullet",
    timerLabelBlits: "Blitz",
    timerLabelTezkor: "Rapid",
    historyAllText: "All",
    historyWinsText: "Wins",
    historyLossesText: "Losses",
    historyDrawsText: "Draws",
    colDate: "Date",
    colOpponent: "Opponent",
    colMode: "Mode",
    colTime: "Time",
    colResult: "Result",
    leaguesDesc: "Continental tournaments refreshed monthly",
    leagueAsia: "Asia League",
    leagueEurope: "Europe League",
    leagueAfrica: "Africa League",
    leagueSouthAmerica: "South America League",
    leagueNorthAmerica: "North America League",
    leagueOceania: "Oceania League",
    leagueCardTeams: "{count} teams • Round-Robin",
    leagueCardDesc: "All teams play each other. The team with the most points wins!",
    leaguePlayAlert: "{mode} - League • {count} teams are ready to play!",
    leagueTableRank: "POS",
    leagueTableTeam: "TEAM",
    leagueStandingsTitle: "Tournament standings",
    championWinnerLabel: "Winner: Team name",
    championsTitle: "Champions League",
    championsSubtitle: "6 continental league winners compete for the grand prize",
    tournamentFormatTitle: "Tournament Format (Round-Robin)",
    roundRobinRule1: "All teams in each league play in Round-Robin format",
    roundRobinRule2: "All teams play each other once (28 games total)",
    roundRobinRule3: "Win: +3 points, Draw: +1 point, Loss: +0 points",
    roundRobinRule4: "The team with the most points becomes league champion",
    settingsTitle: "Settings",
    settingsSubtitle: "Your personal preferences",
    settingsCountryTitle: "🌍 Country flag",
    settingsCountryLabel: "Country code:",
    settingsLanguageTitle: "🗣️ Interface language",
    settingsLanguageLabel: "Language:",
    settingsSoundTitle: "🔊 Sound",
    settingsSoundLabel: "Sound:",
    settingsVolumeLabel: "Volume:",
    settingsDesignTitle: "🎨 Design",
    settingsThemeLabel: "Board theme:",
    settingsCoordsLabel: "Coordinates:",
    settingsSaveBtn: "Save",
    settingsResetBtn: "Reset",
    continentAll: "All",
    continentAsia: "Asia",
    continentEurope: "Europe",
    continentAfrica: "Africa",
    continentSouthAmerica: "South America",
    continentNorthAmerica: "North America",
    continentOceania: "Oceania",
    clubDetailBack: "Back",
    clubDetailMembersCount: "members",
    clubDetailEventsCount: "events",
    clubDetailMembersCard: "Members",
    clubDetailEventsCard: "Events Played",
    clubDetailPointsCard: "Club Points",
    clubDetailAboutTitle: "About Club",
    clubDetailAboutText: "Welcome to the official {country} Chess Club! We are a community of passionate chess players dedicated to improving our skills, organizing tournaments, and promoting chess in {country}. Join us to compete, learn, and connect!",
    clubDetailJoinBtn: "Join Club",
    clubDetailLeaveBtn: "Leave Club",
    clubDetailTournamentsBtn: "Tournaments",
    clubDetailHistoryBtn: "History",
    clubDetailAllClubsBtn: "All Clubs",
    clubDetailTopPlayersTitle: "Top Players",
    clubDetailNoMembers: "No members yet. Be the first to join!",
    loadingText: "Loading...",
    clubLeagueTitle: "{country} League Calendar",
    clubLeagueDesc: "League matches this club participates in",
    clubLeagueRoundRobin: "Round-Robin • {count} teams",
    clubLeagueBadge: "League schedule",
    clubLeagueRound: "Round",
    clubLeagueClub: "Club",
    clubLeagueOpponent: "Opponent",
    clubLeagueVenue: "Venue",
    clubLeagueDate: "Date",
    clubLeagueTime: "Time",
    clubLeagueHome: "Home",
    clubLeagueAway: "Away",
    clubHistoryTitle: "{country} - Members History",
    clubHistoryDesc: "Club members and their join dates",
    clubHistoryEmpty: "No club members yet",
    clubHistoryGamesCard: "Games",
    clubHistoryMembersList: "{count} member(s) (newest first)",
    clubHistoryJoined: "Joined:",
    clubHistoryJoinUnknown: "Unknown",
  },
  ru: {
    mHome: "Главная",
    mPlay: "Играть",
    mLeaderboard: "Рейтинг",
    mHistory: "История игр",
    loginText: "Войти",
    profileText: "Профиль",
    dashWelcomeTitle: "Добро пожаловать, любитель шахмат!",
    dashDesc: "Играйте в шахматы, отслеживайте статистику и повышайте свой рейтинг.",
    dashStartBtn: "Начать игру",
    streakText: "Дней подряд",
    panelStatsHeader: "Статистика",
    labelWhiteWins: "Победы белых:",
    labelBlackWins: "Победы черных:",
    labelDraws: "Ничьи:",
    btnResetStats: "Сброс",
    btnNewGame: "Новая 🔄",
    btnResign: "Сдаться 🏳️",
    panelHistoryHeader: "История",
    whiteText: "Белые",
    blackText: "Черные",
    whiteTimeUp: "Время белых истекло!",
    blackTimeUp: "Время черных истекло!",
    whiteResigned: "Белые сдались!",
    blackResigned: "Черные сдались!",
    drawConfirm: "Согласны на ничью?",
    drawAlert: "Ничья!",
    leaderboardSoon: "Таблица лидеров скоро появится!",
    loginCardTitle: "Вход",
    labelLoginUsername: "Имя пользователя",
    labelLoginPassword: "Пароль",
    btnLoginSubmit: "Войти",
    noAccountText: "Нет аккаунта?",
    goToRegisterLink: "Регистрация",
    regCardTitle: "Регистрация",
    labelRegUsername: "Имя пользователя",
    labelRegEmail: "Почта",
    labelRegPassword: "Пароль",
    btnRegSubmit: "Зарегистрироваться",
    hasAccountText: "Уже есть аккаунт?",
    goToLoginLink: "Войти",
    profileCardTitle: "Профиль",
    profLabelWins: "Победы белых:",
    profLabelLosses: "Победы черных:",
    profLabelDraws: "Ничьи:",
    profLabelRating: "Рейтинг:",
    btnLogout: "Выйти",
    profRatingsBtn: "Рейтинги",
    profEditBtn: "Изменить",
    profSaveBtn: "Сохранить",
    profRapidRating: "РЕЙТИНГ RAPID",
    profBlitzRating: "РЕЙТИНГ BLITZ",
    profBulletRating: "РЕЙТИНГ BULLET",
    profBestOpening: "ЛУЧШИЙ ДЕБЮТ",
    profClubLabel: "КЛУБ",
    profStatusLabel: "СТАТУС",
    profStatusActive: "Активный игрок",
    profFideIdLabel: "FIDE ID",
    profGoalLabel: "Цель",
    profCopyLinkBtn: "Скопировать ссылку на профиль",
    fillAllFields: "Заполните все поля!",
    userExists: "Пользователь уже существует!",
    wrongCredentials: "Неверные данные!",
    regSuccess: "Успешная регистрация!",
    leaderboardTitle: "Рейтинг игроков",
    leaderboardDesc: "Полный рейтинг всех игроков по победам",
    historyTitle: "История игр",
    historyDesc: "Список ваших последних игр",
    dashPlayerTitle: "Топ 5 победителей",
    dashPlayerDesc: "Чемпионы с наибольшим количеством побед.",
    onlineMode: "Онлайн режим",
    createRoom: "Создать комнату",
    joinRoom: "Присоединиться",
    roomCode: "Код комнаты",
    enterRoomCode: "Введите код комнаты",
    drawOffer: "Предложение ничьей",
    drawOffered: "Соперник предложил ничью!",
    drawAccepted: "Ничья принята!",
    drawDeclined: "Ничья отклонена!",
    pgnExport: "PGN экспорт",
    pgnDownloaded: "PGN файл загружен!",
    tournamentsTitle: "Турниры",
    tournamentsDesc: "Арена-турниры каждый час в течение 24 часов",
    clubsTitle: "Клубы",
    clubsDesc: "Шахматные клубы и сообщества",
    btnCreateClub: "+ Создать клуб",
    chatTitle: "Чат",
    chatDesc: "Сообщения и разговоры",
    btnSendChatMessage: "Отправить",
    mChat: "Чат",
    playOnlineBtn: "Играть онлайн",
    tabPlayers: "Игроки",
    tabClubs: "Клубы",
    searchCountry: "Поиск страны...",
    filterAll: "Все",
    filterRapid: "Рапид",
    filterBlitz: "Блиц",
    filterBullet: "Пуля",
    btnView: "Просмотр",
    membersLabel: "участников",
    colUsername: "Имя пользователя",
    colRating: "Рейтинг",
    colWinPoints: "Очки побед",
    colWins: "Победы",
    colGames: "Игры",
    colWinPercent: "% побед",
    colPlayer: "Игрок",
    mLeagues: "Лиги",
    mChampions: "Чемпионы",
    mSettings: "Настройки",
    waitingSearching: "Поиск соперника...",
    waitingPlease: "Пожалуйста, подождите",
    historyPanelHeader: "История ходов",
    ratedLabel: "Рейтинговая",
    ratedSublabel: "Режим игры",
    btnDrawText: "Ничья",
    btnPgnText: "PGN",
    btnStartGameText: "Начать игру",
    timerLabelJudaTez: "Пуля",
    timerLabelBlits: "Блиц",
    timerLabelTezkor: "Рапид",
    historyAllText: "Все",
    historyWinsText: "Победы",
    historyLossesText: "Поражения",
    historyDrawsText: "Ничьи",
    colDate: "Дата",
    colOpponent: "Соперник",
    colMode: "Режим",
    colTime: "Время",
    colResult: "Результат",
    leaguesDesc: "Континентальные турниры каждый месяц",
    leagueAsia: "Азиатская лига",
    leagueEurope: "Европейская лига",
    leagueAfrica: "Африканская лига",
    leagueSouthAmerica: "Лига Южной Америки",
    leagueNorthAmerica: "Лига Северной Америки",
    leagueOceania: "Океанская лига",
    leagueCardTeams: "{count} команд • Round-Robin",
    leagueCardDesc: "Все команды играют друг с другом. Побеждает команда с наибольшим числом очков!",
    leaguePlayAlert: "{mode} - Лига • {count} команд готовы играть!",
    leagueTableRank: "МЕСТО",
    leagueTableTeam: "КОМАНДА",
    leagueStandingsTitle: "Турнирная таблица",
    championWinnerLabel: "Победитель: название команды",
    championsTitle: "Чемпионы",
    championsSubtitle: "6 победителей лиг борются за большой приз",
    tournamentFormatTitle: "Формат турнира (Round-Robin)",
    roundRobinRule1: "Все команды каждой лиги играют в формате Round-Robin",
    roundRobinRule2: "Все команды играют друг с другом по одному разу (28 игр всего)",
    roundRobinRule3: "Победа: +3 очка, Ничья: +1 очко, Поражение: +0 очков",
    roundRobinRule4: "Команда, набрашая больше всего очков, становится чемпионом лиги",
    settingsTitle: "Настройки",
    settingsSubtitle: "Ваши личные предпочтения",
    settingsCountryTitle: "🌍 Флаг страны",
    settingsCountryLabel: "Код страны:",
    settingsLanguageTitle: "🗣️ Язык интерфейса",
    settingsLanguageLabel: "Язык:",
    settingsSoundTitle: "🔊 Звук",
    settingsSoundLabel: "Звук:",
    settingsVolumeLabel: "Громкость:",
    settingsDesignTitle: "🎨 Дизайн",
    settingsThemeLabel: "Тема доски:",
    settingsCoordsLabel: "Координаты:",
    settingsSaveBtn: "Сохранить",
    settingsResetBtn: "Сброс",
    continentAll: "Все",
    continentAsia: "Азия",
    continentEurope: "Европа",
    continentAfrica: "Африка",
    continentSouthAmerica: "Южная Америка",
    continentNorthAmerica: "Северная Америка",
    continentOceania: "Океания",
    clubDetailBack: "Назад",
    clubDetailMembersCount: "участников",
    clubDetailEventsCount: "турниров",
    clubDetailMembersCard: "Участники",
    clubDetailEventsCard: "Проведённые турниры",
    clubDetailPointsCard: "Очки клуба",
    clubDetailAboutTitle: "О клубе",
    clubDetailAboutText: "Добро пожаловать в официальный шахматный клуб {country}! Мы — сообщество увлечённых шахматистов, стремящихся повышать своё мастерство, организовывать турниры и развивать шахматы в {country}. Присоединяйтесь, чтобы играть, учиться и общаться!",
    clubDetailJoinBtn: "Вступить в клуб",
    clubDetailLeaveBtn: "Покинуть клуб",
    clubDetailTournamentsBtn: "Турниры",
    clubDetailHistoryBtn: "История",
    clubDetailAllClubsBtn: "Все клубы",
    clubDetailTopPlayersTitle: "Лучшие игроки",
    clubDetailNoMembers: "Пока нет участников. Станьте первым!",
    loadingText: "Загрузка...",
    clubLeagueTitle: "Календарь лиги {country}",
    clubLeagueDesc: "Матчи лиги, в которых участвует этот клуб",
    clubLeagueRoundRobin: "Round-Robin • {count} команд",
    clubLeagueBadge: "Календарь лиги",
    clubLeagueRound: "Тур",
    clubLeagueClub: "Клуб",
    clubLeagueOpponent: "Соперник",
    clubLeagueVenue: "Площадка",
    clubLeagueDate: "Дата",
    clubLeagueTime: "Время",
    clubLeagueHome: "Дома",
    clubLeagueAway: "В гостях",
    clubHistoryTitle: "{country} - История участников",
    clubHistoryDesc: "Участники клуба и даты их присоединения",
    clubHistoryEmpty: "В клубе пока нет участников",
    clubHistoryGamesCard: "Игры",
    clubHistoryMembersList: "{count} участник(ов) (сначала новые)",
    clubHistoryJoined: "Присоединился:",
    clubHistoryJoinUnknown: "Неизвестно",
  },
  es: {
    mHome: "Inicio",
    mPlay: "Jugar",
    mLeaderboard: "Clasificación",
    mHistory: "Historial",
    loginText: "Entrar",
    profileText: "Perfil",
    dashWelcomeTitle: "¡Bienvenido, entusiasta del ajedrez!",
    dashDesc: "Juega al ajedrez profesional, sigue tus estadísticas y mejora tu clasificación.",
    dashStartBtn: "Empezar a jugar",
    streakText: "Días seguidos",
    panelStatsHeader: "Estadísticas",
    labelWhiteWins: "Victorias blancas:",
    labelBlackWins: "Victorias negras:",
    labelDraws: "Empates:",
    btnResetStats: "Borrar",
    btnNewGame: "Nueva 🔄",
    btnResign: "Rendirse 🏳️",
    panelHistoryHeader: "Historial",
    whiteText: "Blancas",
    blackText: "Negras",
    whiteTimeUp: "¡Se acabó el tiempo de blancas!",
    blackTimeUp: "¡Se acabó el tiempo de negras!",
    whiteResigned: "¡Blancas se rindieron!",
    blackResigned: "¡Negras se rindieron!",
    drawConfirm: "¿Aceptas el empate?",
    drawAlert: "¡Empate!",
    leaderboardSoon: "¡Clasificación próximamente!",
    loginCardTitle: "Iniciar sesión",
    labelLoginUsername: "Usuario",
    labelLoginPassword: "Contraseña",
    btnLoginSubmit: "Entrar",
    noAccountText: "¿No tienes cuenta?",
    goToRegisterLink: "Registrarse",
    regCardTitle: "Registro",
    labelRegUsername: "Usuario",
    labelRegEmail: "Correo",
    labelRegPassword: "Contraseña",
    btnRegSubmit: "Registrarse",
    hasAccountText: "¿Ya tienes cuenta?",
    goToLoginLink: "Entrar",
    profileCardTitle: "Perfil",
    profLabelWins: "Victorias blancas:",
    profLabelLosses: "Victorias negras:",
    profLabelDraws: "Empates:",
    profLabelRating: "Clasificación:",
    btnLogout: "Cerrar sesión",
    profRatingsBtn: "Clasificaciones",
    profEditBtn: "Editar",
    profSaveBtn: "Guardar",
    profRapidRating: "CLASIFICACIÓN RAPID",
    profBlitzRating: "CLASIFICACIÓN BLITZ",
    profBulletRating: "CLASIFICACIÓN BULLET",
    profBestOpening: "MEJOR APERTURA",
    profClubLabel: "CLUB",
    profStatusLabel: "ESTADO",
    profStatusActive: "Jugador activo",
    profFideIdLabel: "FIDE ID",
    profGoalLabel: "Objetivo",
    profCopyLinkBtn: "Copiar enlace del perfil",
    fillAllFields: "¡Rellena todos los campos!",
    userExists: "¡Usuario ya existe!",
    wrongCredentials: "¡Datos incorrectos!",
    regSuccess: "¡Registrado con éxito!",
    leaderboardTitle: "Clasificación de jugadores",
    leaderboardDesc: "Ranking completo de todos los jugadores por victorias",
    historyTitle: "Historial de partidas",
    historyDesc: "Lista de tus partidas recientes",
    dashPlayerTitle: "Top 5 Ganadores",
    dashPlayerDesc: "Campeones con más victorias.",
    onlineMode: "Modo online",
    createRoom: "Crear sala",
    joinRoom: "Unirse",
    roomCode: "Código de sala",
    enterRoomCode: "Ingresa el código",
    drawOffer: "Ofrecer empate",
    drawOffered: "¡El oponente ofreció empate!",
    drawAccepted: "¡Empate aceptado!",
    drawDeclined: "¡Empate rechazado!",
    pgnExport: "Exportar PGN",
    pgnDownloaded: "¡Archivo PGN descargado!",
tournamentsTitle: "Torneos",
    tournamentsDesc: "Torneos arena cada hora durante 24 horas",
    clubsTitle: "Clubes",
    clubsDesc: "Clubes de ajedrez y comunidades",
    btnCreateClub: "+ Crear Club",
    chatTitle: "Chat",
    chatDesc: "Mensajes y conversaciones",
    btnSendChatMessage: "Enviar",
    mChat: "Chat",
    playOnlineBtn: "Jugar en línea",
    tabPlayers: "Jugadores",
    tabClubs: "Clubes",
    searchCountry: " Buscar un país...",
    filterAll: "Todos",
    filterRapid: "Rápidas",
    filterBlitz: "Blitz",
    filterBullet: "Bala",
    btnView: "Ver",
    membersLabel: "miembros",
    colUsername: "Usuario",
    colRating: "Clasificación",
    colWinPoints: "Puntos de victoria",
    colWins: "Victorias",
    colGames: "Partidas",
    colWinPercent: "% Victorias",
    colPlayer: "Jugador",
    mLeagues: "Ligas",
    mChampions: "Campeones",
    mSettings: "Ajustes",
    waitingSearching: "Buscando oponente...",
    waitingPlease: "Por favor espera",
    historyPanelHeader: "Historial de jugadas",
    ratedLabel: "Clasificatoria",
    ratedSublabel: "Modo de juego",
    btnDrawText: "Tablas",
    btnPgnText: "PGN",
    btnStartGameText: "Empezar partida",
    timerLabelJudaTez: "Bala",
    timerLabelBlits: "Blitz",
    timerLabelTezkor: "Rápidas",
    historyAllText: "Todo",
    historyWinsText: "Victorias",
    historyLossesText: "Derrotas",
    historyDrawsText: "Tablas",
    colDate: "Fecha",
    colOpponent: "Oponente",
    colMode: "Modo",
    colTime: "Tiempo",
    colResult: "Resultado",
    leaguesDesc: "Torneos continentales actualizados mensualmente",
    leagueAsia: "Liga de Asia",
    leagueEurope: "Liga de Europa",
    leagueAfrica: "Liga de África",
    leagueSouthAmerica: "Liga de Sudamérica",
    leagueNorthAmerica: "Liga de Norteamérica",
    leagueOceania: "Liga de Oceanía",
    leagueCardTeams: "{count} equipos • Round-Robin",
    leagueCardDesc: "Todos los equipos se enfrentan entre sí. ¡Gana el equipo con más puntos!",
    leaguePlayAlert: "{mode} - Liga • ¡{count} equipos listos para jugar!",
    leagueTableRank: "POS",
    leagueTableTeam: "EQUIPO",
    leagueStandingsTitle: "Clasificación del torneo",
    championWinnerLabel: "Ganador: Nombre del equipo",
    championsTitle: "Liga de Campeones",
    championsSubtitle: "6 ganadores de ligas continentales compiten por el gran premio",
    tournamentFormatTitle: "Formato de Torneo (Round-Robin)",
    roundRobinRule1: "Todos los equipos de cada liga juegan en formato Round-Robin",
    roundRobinRule2: "Todos los equipos juegan entre sí una vez (28 partidas en total)",
    roundRobinRule3: "Victoria: +3 puntos, Empate: +1 punto, Derrota: +0 puntos",
    roundRobinRule4: "El equipo con más puntos se corona campeón de la liga",
    settingsTitle: "Ajustes",
    settingsSubtitle: "Tus preferencias personales",
    settingsCountryTitle: "🌍 Bandera del país",
    settingsCountryLabel: "Código de país:",
    settingsLanguageTitle: "🗣️ Idioma de la interfaz",
    settingsLanguageLabel: "Idioma:",
    settingsSoundTitle: "🔊 Sonido",
    settingsSoundLabel: "Sonido:",
    settingsVolumeLabel: "Volumen:",
    settingsDesignTitle: "🎨 Diseño",
    settingsThemeLabel: "Tema del tablero:",
    settingsCoordsLabel: "Coordenadas:",
    settingsSaveBtn: "Guardar",
    settingsResetBtn: "Reiniciar",
    continentAll: "Todos",
    continentAsia: "Asia",
    continentEurope: "Europa",
    continentAfrica: "África",
    continentSouthAmerica: "Sudamérica",
    continentNorthAmerica: "Norteamérica",
    continentOceania: "Oceanía",
    clubDetailBack: "Volver",
    clubDetailMembersCount: "miembros",
    clubDetailEventsCount: "torneos",
    clubDetailMembersCard: "Miembros",
    clubDetailEventsCard: "Torneos disputados",
    clubDetailPointsCard: "Puntos del club",
    clubDetailAboutTitle: "Sobre el club",
    clubDetailAboutText: "¡Bienvenido al Club de Ajedrez oficial de {country}! Somos una comunidad de apasionados jugadores de ajedrez dedicados a mejorar nuestro nivel, organizar torneos y promover el ajedrez en {country}. ¡Únete para competir, aprender y conectar!",
    clubDetailJoinBtn: "Unirse al club",
    clubDetailLeaveBtn: "Salir del club",
    clubDetailTournamentsBtn: "Torneos",
    clubDetailHistoryBtn: "Historia",
    clubDetailAllClubsBtn: "Todos los clubes",
    clubDetailTopPlayersTitle: "Mejores jugadores",
    clubDetailNoMembers: "Aún no hay miembros. ¡Únete tú primero!",
    loadingText: "Cargando...",
    clubLeagueTitle: "Calendario de la liga {country}",
    clubLeagueDesc: "Partidos de liga en los que participa este club",
    clubLeagueRoundRobin: "Round-Robin • {count} equipos",
    clubLeagueBadge: "Calendario de liga",
    clubLeagueRound: "Jornada",
    clubLeagueClub: "Club",
    clubLeagueOpponent: "Rival",
    clubLeagueVenue: "Sede",
    clubLeagueDate: "Fecha",
    clubLeagueTime: "Hora",
    clubLeagueHome: "Casa",
    clubLeagueAway: "Fuera",
    clubHistoryTitle: "{country} - Historial de miembros",
    clubHistoryDesc: "Miembros del club y sus fechas de incorporación",
    clubHistoryEmpty: "Aún no hay miembros en el club",
    clubHistoryGamesCard: "Partidas",
    clubHistoryMembersList: "{count} miembro(s) (del más reciente al más antiguo)",
    clubHistoryJoined: "Se unió:",
    clubHistoryJoinUnknown: "Desconocido",
  },
  de: {
    mHome: "Startseite",
    mPlay: "Spielen",
    mLeaderboard: "Rangliste",
    mHistory: "Verlauf",
    loginText: "Anmelden",
    profileText: "Profil",
    dashWelcomeTitle: "Willkommen, Schachliebhaber!",
    dashDesc: "Spiele professionelles Schach, verfolge deine Statistiken und steigere deine Bewertung.",
    dashStartBtn: "Spiel starten",
    streakText: "Tage in Folge",
    panelStatsHeader: "Statistiken",
    labelWhiteWins: "Weiße Siege:",
    labelBlackWins: "Schwarze Siege:",
    labelDraws: "Unentschieden:",
    btnResetStats: "Zurücksetzen",
    btnNewGame: "Neu 🔄",
    btnResign: "Aufgeben 🏳️",
    panelHistoryHeader: "Verlauf",
    whiteText: "Weiß",
    blackText: "Schwarz",
    whiteTimeUp: "Weiß Zeit abgelaufen!",
    blackTimeUp: "Schwarz Zeit abgelaufen!",
    whiteResigned: "Weiß hat aufgegeben!",
    blackResigned: "Schwarz hat aufgegeben!",
    drawConfirm: "Unentschieden annehmen?",
    drawAlert: "Unentschieden!",
    leaderboardSoon: "Rangliste demnächst!",
    loginCardTitle: "Anmelden",
    labelLoginUsername: "Benutzername",
    labelLoginPassword: "Passwort",
    btnLoginSubmit: "Anmelden",
    noAccountText: "Kein Konto?",
    goToRegisterLink: "Registrieren",
    regCardTitle: "Registrierung",
    labelRegUsername: "Benutzername",
    labelRegEmail: "E-Mail",
    labelRegPassword: "Passwort",
    btnRegSubmit: "Registrieren",
    hasAccountText: "Bereits ein Konto?",
    goToLoginLink: "Anmelden",
    profileCardTitle: "Profil",
    profLabelWins: "Weiße Siege:",
    profLabelLosses: "Schwarze Siege:",
    profLabelDraws: "Unentschieden:",
    profLabelRating: "Bewertung:",
    btnLogout: "Abmelden",
    profRatingsBtn: "Bewertungen",
    profEditBtn: "Bearbeiten",
    profSaveBtn: "Speichern",
    profRapidRating: "RAPID-BEWERTUNG",
    profBlitzRating: "BLITZ-BEWERTUNG",
    profBulletRating: "BULLET-BEWERTUNG",
    profBestOpening: "BESTE ERÖFFNUNG",
    profClubLabel: "VEREIN",
    profStatusLabel: "STATUS",
    profStatusActive: "Aktiver Spieler",
    profFideIdLabel: "FIDE-ID",
    profGoalLabel: "Ziel",
    profCopyLinkBtn: "Profil-Link kopieren",
    fillAllFields: "Bitte alle Felder ausfüllen!",
    userExists: "Benutzer existiert bereits!",
    wrongCredentials: "Falsche Daten!",
    regSuccess: "Erfolgreich registriert!",
    leaderboardTitle: "Spieler-Rangliste",
    leaderboardDesc: "Vollständige Rangliste aller Spieler nach Siegen",
    historyTitle: "Spielverlauf",
    historyDesc: "Liste deiner letzten Spiele",
    dashPlayerTitle: "Top 5 Gewinner",
    dashPlayerDesc: "Meiste Siege.",
    onlineMode: "Online-Modus",
    createRoom: "Raum erstellen",
    joinRoom: "Beitreten",
    roomCode: "Raumcode",
    enterRoomCode: "Raumcode eingeben",
    drawOffer: "Unentschieden anbieten",
    drawOffered: "Gegner bietet Unentschieden an!",
    drawAccepted: "Unentschieden angenommen!",
    drawDeclined: "Unentschieden abgelehnt!",
    pgnExport: "PGN Export",
    pgnDownloaded: "PGN Datei heruntergeladen!",
    tournamentsTitle: "Turniere",
    tournamentsDesc: "Arena-Turniere jede Stunde, 24 Stunden lang",
    clubsTitle: "Clubs",
    clubsDesc: "Schachclubs und Gemeinschaften",
    btnCreateClub: "+ Club erstellen",
    chatTitle: "Chat",
    chatDesc: "Nachrichten und Gespräche",
    btnSendChatMessage: "Senden",
    mChat: "Chat",
    playOnlineBtn: "Online spielen",
    tabPlayers: "Spieler",
    tabClubs: "Clubs",
    searchCountry: "Land suchen...",
    filterAll: "Alle",
    filterRapid: "Rapid",
    filterBlitz: "Blitz",
    filterBullet: "Bullet",
    btnView: "Ansehen",
    membersLabel: "Mitglieder",
    colUsername: "Benutzername",
    colRating: "Bewertung",
    colWinPoints: "Siegpunkte",
    colWins: "Siege",
    colGames: "Spiele",
    colWinPercent: "Sieg %",
    colPlayer: "Spieler",
    mLeagues: "Ligen",
    mChampions: "Champions",
    mSettings: "Einstellungen",
    waitingSearching: "Gegner wird gesucht...",
    waitingPlease: "Bitte warten",
    historyPanelHeader: "Zugverlauf",
    ratedLabel: "Gewertet",
    ratedSublabel: "Spielmodus",
    btnDrawText: "Remis",
    btnPgnText: "PGN",
    btnStartGameText: "Spiel starten",
    timerLabelJudaTez: "Bullet",
    timerLabelBlits: "Blitz",
    timerLabelTezkor: "Rapid",
    historyAllText: "Alle",
    historyWinsText: "Siege",
    historyLossesText: "Niederlagen",
    historyDrawsText: "Unentschieden",
    colDate: "Datum",
    colOpponent: "Gegner",
    colMode: "Modus",
    colTime: "Zeit",
    colResult: "Ergebnis",
    leaguesDesc: "Kontinentale Turniere monatlich aktualisiert",
    leagueAsia: "Asien-Liga",
    leagueEurope: "Europa-Liga",
    leagueAfrica: "Afrika-Liga",
    leagueSouthAmerica: "Südamerika-Liga",
    leagueNorthAmerica: "Nordamerika-Liga",
    leagueOceania: "Ozeanien-Liga",
    leagueCardTeams: "{count} Mannschaften • Round-Robin",
    leagueCardDesc: "Alle Mannschaften spielen gegeneinander. Das Team mit den meisten Punkten gewinnt!",
    leaguePlayAlert: "{mode} - Liga • {count} Mannschaften sind spielbereit!",
    leagueTableRank: "PL.",
    leagueTableTeam: "MANNSCHAFT",
    leagueStandingsTitle: "Turniertabelle",
    championWinnerLabel: "Sieger: Mannschaftsname",
    championsTitle: "Champions League",
    championsSubtitle: "6 kontinentale Ligasieger kämpfen um den Großen Preis",
    tournamentFormatTitle: "Turnierformat (Round-Robin)",
    roundRobinRule1: "Alle Mannschaften jeder Liga spielen im Round-Robin-Format",
    roundRobinRule2: "Alle Mannschaften spielen einander einmal aus (28 Spiele insgesamt)",
    roundRobinRule3: "Sieg: +3 Punkte, Unentschieden: +1 Punkt, Niederlage: +0 Punkte",
    roundRobinRule4: "Die Mannschaft mit den meisten Punkten wird Ligameister",
    settingsTitle: "Einstellungen",
    settingsSubtitle: "Ihre persönlichen Vorlieben",
    settingsCountryTitle: "🌍 Länderflagge",
    settingsCountryLabel: "Ländercode:",
    settingsLanguageTitle: "🗣️ Sprache der Oberfläche",
    settingsLanguageLabel: "Sprache:",
    settingsSoundTitle: "🔊 Sound",
    settingsSoundLabel: "Sound:",
    settingsVolumeLabel: "Lautstärke:",
    settingsDesignTitle: "🎨 Design",
    settingsThemeLabel: "Brettthema:",
    settingsCoordsLabel: "Koordinaten:",
    settingsSaveBtn: "Speichern",
    settingsResetBtn: "Zurücksetzen",
    continentAll: "Alle",
    continentAsia: "Asien",
    continentEurope: "Europa",
    continentAfrica: "Afrika",
    continentSouthAmerica: "Südamerika",
    continentNorthAmerica: "Nordamerika",
    continentOceania: "Ozeanien",
    clubDetailBack: "Zurück",
    clubDetailMembersCount: "Mitglieder",
    clubDetailEventsCount: "Turniere",
    clubDetailMembersCard: "Mitglieder",
    clubDetailEventsCard: "Ausgetragene Turniere",
    clubDetailPointsCard: "Vereinspunkte",
    clubDetailAboutTitle: "Über den Verein",
    clubDetailAboutText: "Willkommen beim offiziellen Schachclub {country}! Wir sind eine Gemeinschaft leidenschaftlicher Schachspieler, die ihr Können verbessern, Turniere organisieren und Schach in {country} fördern. Tritt uns bei, um zu spielen, zu lernen und Kontakte zu knüpfen!",
    clubDetailJoinBtn: "Verein beitreten",
    clubDetailLeaveBtn: "Verein verlassen",
    clubDetailTournamentsBtn: "Turniere",
    clubDetailHistoryBtn: "Geschichte",
    clubDetailAllClubsBtn: "Alle Vereine",
    clubDetailTopPlayersTitle: "Beste Spieler",
    clubDetailNoMembers: "Noch keine Mitglieder. Sei die/r Erste!",
    loadingText: "Wird geladen...",
    clubLeagueTitle: "Ligakalender {country}",
    clubLeagueDesc: "Ligaspiele, an denen dieser Verein teilnimmt",
    clubLeagueRoundRobin: "Round-Robin • {count} Mannschaften",
    clubLeagueBadge: "Ligaspielplan",
    clubLeagueRound: "Runde",
    clubLeagueClub: "Verein",
    clubLeagueOpponent: "Gegner",
    clubLeagueVenue: "Spielfeld",
    clubLeagueDate: "Datum",
    clubLeagueTime: "Uhrzeit",
    clubLeagueHome: "Heim",
    clubLeagueAway: "Auswärts",
    clubHistoryTitle: "{country} - Mitgliederhistorie",
    clubHistoryDesc: "Vereinsmitglieder und ihr Beitrittsdatum",
    clubHistoryEmpty: "Noch keine Vereinsmitglieder",
    clubHistoryGamesCard: "Spiele",
    clubHistoryMembersList: "{count} Mitglied(er) (neueste zuerst)",
    clubHistoryJoined: "Beigetreten:",
    clubHistoryJoinUnknown: "Unbekannt",
  },
  fr: {
    mHome: "Accueil",
    mPlay: "Jouer",
    mLeaderboard: "Classement",
    mHistory: "Historique",
    loginText: "Connexion",
    profileText: "Profil",
    dashWelcomeTitle: "Bienvenue, amateur d'échecs!",
    dashDesc: "Jouez aux échecs professionnels, suivez vos statistiques et améliorez votre classement.",
    dashStartBtn: "Commencer à jouer",
    streakText: "Jours consécutifs",
    panelStatsHeader: "Statistiques",
    labelWhiteWins: "Victoires blancs:",
    labelBlackWins: "Victoires noirs:",
    labelDraws: "Nuls:",
    btnResetStats: "Réinitialiser",
    btnNewGame: "Nouveau 🔄",
    btnResign: "Abandonner 🏳️",
    panelHistoryHeader: "Historique",
    whiteText: "Blancs",
    blackText: "Noirs",
    whiteTimeUp: "Temps des blancs écoulé!",
    blackTimeUp: "Temps des noirs écoulé!",
    whiteResigned: "Blancs ont abandonné!",
    blackResigned: "Noirs ont abandonné!",
    drawConfirm: "Accepter le match nul?",
    drawAlert: "Match nul!",
    leaderboardSoon: "Classement bientôt!",
    loginCardTitle: "Connexion",
    labelLoginUsername: "Nom d'utilisateur",
    labelLoginPassword: "Mot de passe",
    btnLoginSubmit: "Connexion",
    noAccountText: "Pas de compte?",
    goToRegisterLink: "S'inscrire",
    regCardTitle: "Inscription",
    labelRegUsername: "Nom d'utilisateur",
    labelRegEmail: "Email",
    labelRegPassword: "Mot de passe",
    btnRegSubmit: "S'inscrire",
    hasAccountText: "Vous avez déjà un compte?",
    goToLoginLink: "Connexion",
    profileCardTitle: "Profil",
    profLabelWins: "Victoires blancs:",
    profLabelLosses: "Victoires noirs:",
    profLabelDraws: "Nuls:",
    profLabelRating: "Classement:",
    btnLogout: "Déconnexion",
    profRatingsBtn: "Classements",
    profEditBtn: "Modifier",
    profSaveBtn: "Enregistrer",
    profRapidRating: "CLASSEMENT RAPID",
    profBlitzRating: "CLASSEMENT BLITZ",
    profBulletRating: "CLASSEMENT BULLET",
    profBestOpening: "MEILLEURE OUVERTURE",
    profClubLabel: "CLUB",
    profStatusLabel: "STATUT",
    profStatusActive: "Joueur actif",
    profFideIdLabel: "FIDE ID",
    profGoalLabel: "Objectif",
    profCopyLinkBtn: "Copier le lien du profil",
    fillAllFields: "Remplissez tous les champs!",
    userExists: "Utilisateur existe déjà!",
    wrongCredentials: "Données incorrectes!",
    regSuccess: "Inscription réussie!",
    leaderboardTitle: "Classement des joueurs",
    leaderboardDesc: "Classement complet de tous les joueurs par victoires",
    historyTitle: "Historique des parties",
    historyDesc: "Liste de vos parties récentes",
    dashPlayerTitle: "Top 5 Gagnants",
    dashPlayerDesc: "Champions avec le plus de victoires.",
    onlineMode: "Mode en ligne",
    createRoom: "Créer une salle",
    joinRoom: "Rejoindre",
    roomCode: "Code de salle",
    enterRoomCode: "Entrez le code",
    drawOffer: "Offrir match nul",
    drawOffered: "L'adversaire propose un match nul!",
    drawAccepted: "Match nul accepté!",
    drawDeclined: "Match nul refusé!",
    pgnExport: "Exporter PGN",
    pgnDownloaded: "Fichier PGN téléchargé!",
    tournamentsTitle: "Tournois",
    tournamentsDesc: "Tournois arena toutes les heures pendant 24 heures",
    clubsTitle: "Clubs",
    clubsDesc: "Clubs d'échecs et communautés",
    btnCreateClub: "+ Créer un club",
    chatTitle: "Chat",
    chatDesc: "Messages et conversations",
    btnSendChatMessage: "Envoyer",
    mChat: "Chat",
    playOnlineBtn: "Jouer en ligne",
    tabPlayers: "Joueurs",
    tabClubs: "Clubs",
    searchCountry: "Rechercher un pays...",
    filterAll: "Tous",
    filterRapid: "Cadence",
    filterBlitz: "Blitz",
    filterBullet: "Bullet",
    btnView: "Voir",
    membersLabel: "membres",
    colUsername: "Nom d'utilisateur",
    colRating: "Classement",
    colWinPoints: "Points de victoire",
    colWins: "Victoires",
    colGames: "Parties",
    colWinPercent: "% Victoires",
    colPlayer: "Joueur",
    mLeagues: "Ligues",
    mChampions: "Champions",
    mSettings: "Paramètres",
    waitingSearching: "Recherche d'adversaire...",
    waitingPlease: "Veuillez patienter",
    historyPanelHeader: "Historique des coups",
    ratedLabel: "Classée",
    ratedSublabel: "Mode de jeu",
    btnDrawText: "Nulle",
    btnPgnText: "PGN",
    btnStartGameText: "Démarrer la partie",
    timerLabelJudaTez: "Bullet",
    timerLabelBlits: "Blitz",
    timerLabelTezkor: "Cadence",
    historyAllText: "Tous",
    historyWinsText: "Victoires",
    historyLossesText: "Défaites",
    historyDrawsText: "Nuls",
    colDate: "Date",
    colOpponent: "Adversaire",
    colMode: "Mode",
    colTime: "Temps",
    colResult: "Résultat",
    leaguesDesc: "Tournois continentaux mis à jour mensuellement",
    leagueAsia: "Ligue d'Asie",
    leagueEurope: "Ligue d'Europe",
    leagueAfrica: "Ligue d'Afrique",
    leagueSouthAmerica: "Ligue d'Amérique du Sud",
    leagueNorthAmerica: "Ligue d'Amérique du Nord",
    leagueOceania: "Ligue d'Océanie",
    leagueCardTeams: "{count} équipes • Round-Robin",
    leagueCardDesc: "Toutes les équipes s'affrontent. L'équipe avec le plus de points gagne !",
    leaguePlayAlert: "{mode} - Ligue • {count} équipes prêtes à jouer !",
    leagueTableRank: "POS",
    leagueTableTeam: "ÉQUIPE",
    leagueStandingsTitle: "Classement du tournoi",
    championWinnerLabel: "Gagnant: Nom de l'équipe",
    championsTitle: "Ligue des Champions",
    championsSubtitle: "6 champions de ligues continentales pour le grand prix",
    tournamentFormatTitle: "Format de Tournoi (Round-Robin)",
    roundRobinRule1: "Toutes les équipes de chaque ligue jouent en Round-Robin",
    roundRobinRule2: "Toutes les équipes se jouent une fois (28 matchs au total)",
    roundRobinRule3: "Victoire: +3 points, Nul: +1 point, Défaite: +0 points",
    roundRobinRule4: "L'équipe avec le plus de points devient champion de ligue",
    settingsTitle: "Paramètres",
    settingsSubtitle: "Vos préférences personnelles",
    settingsCountryTitle: "🌍 Drapeau du pays",
    settingsCountryLabel: "Code du pays:",
    settingsLanguageTitle: "🗣️ Langue de l'interface",
    settingsLanguageLabel: "Langue:",
    settingsSoundTitle: "🔊 Son",
    settingsSoundLabel: "Son:",
    settingsVolumeLabel: "Volume:",
    settingsDesignTitle: "🎨 Design",
    settingsThemeLabel: "Thème du tableau:",
    settingsCoordsLabel: "Coordonnées:",
    settingsSaveBtn: "Enregistrer",
    settingsResetBtn: "Réinitialiser",
    continentAll: "Tous",
    continentAsia: "Asie",
    continentEurope: "Europe",
    continentAfrica: "Afrique",
    continentSouthAmerica: "Amérique du Sud",
    continentNorthAmerica: "Amérique du Nord",
    continentOceania: "Océanie",
    clubDetailBack: "Retour",
    clubDetailMembersCount: "membres",
    clubDetailEventsCount: "tournois",
    clubDetailMembersCard: "Membres",
    clubDetailEventsCard: "Tournois disputés",
    clubDetailPointsCard: "Points du club",
    clubDetailAboutTitle: "À propos du club",
    clubDetailAboutText: "Bienvenue au Club d'échecs officiel de {country} ! Nous sommes une communauté de joueurs d'échecs passionnés, engagés à améliorer notre niveau, à organiser des tournois et à promouvoir les échecs en {country}. Rejoignez-nous pour jouer, apprendre et échanger !",
    clubDetailJoinBtn: "Rejoindre le club",
    clubDetailLeaveBtn: "Quitter le club",
    clubDetailTournamentsBtn: "Tournois",
    clubDetailHistoryBtn: "Historique",
    clubDetailAllClubsBtn: "Tous les clubs",
    clubDetailTopPlayersTitle: "Meilleurs joueurs",
    clubDetailNoMembers: "Pas encore de membres. Soyez le premier !",
    loadingText: "Chargement...",
    clubLeagueTitle: "Calendrier de la ligue {country}",
    clubLeagueDesc: "Matchs de ligue auxquels ce club participe",
    clubLeagueRoundRobin: "Round-Robin • {count} équipes",
    clubLeagueBadge: "Calendrier de ligue",
    clubLeagueRound: "Journée",
    clubLeagueClub: "Club",
    clubLeagueOpponent: "Adversaire",
    clubLeagueVenue: "Terrain",
    clubLeagueDate: "Date",
    clubLeagueTime: "Heure",
    clubLeagueHome: "Domicile",
    clubLeagueAway: "Extérieur",
    clubHistoryTitle: "{country} - Historique des membres",
    clubHistoryDesc: "Membres du club et dates d'adhésion",
    clubHistoryEmpty: "Aucun membre dans le club pour l'instant",
    clubHistoryGamesCard: "Parties",
    clubHistoryMembersList: "{count} membre(s) (du plus récent au plus ancien)",
    clubHistoryJoined: "Inscrit le :",
    clubHistoryJoinUnknown: "Inconnu",
  }
};

i18next.init({
  lng: localStorage.getItem("justChessLang") || "uz",
  fallbackLng: "uz",
  debug: false,
  resources: {
    uz: { translation: translations.uz },
    en: { translation: translations.en },
    ru: { translation: translations.ru },
    es: { translation: translations.es },
    de: { translation: translations.de },
    fr: { translation: translations.fr }
  }
}, function(err, t) {
  if (!err) updateUI();
});

function leaderboardAlertText() {
  return i18next.t('leaderboardSoon');
}

function updateUI() {
  const t = (key) => i18next.t(key);

  const mHome = document.getElementById("mHome"); if (mHome) mHome.textContent = t('mHome');
  const mPlay = document.getElementById("mPlay"); if (mPlay) mPlay.textContent = t('mPlay');
  const mLeaderboard = document.getElementById("mLeaderboard"); if (mLeaderboard) mLeaderboard.textContent = t('mLeaderboard');
  const mHistory = document.getElementById("mHistory"); if (mHistory) mHistory.textContent = t('mHistory');
  const mTournaments = document.getElementById("mTournaments"); if (mTournaments) mTournaments.textContent = t('tournamentsTitle');
  const mClubs = document.getElementById("mClubs"); if (mClubs) mClubs.textContent = t('clubsTitle');

  const dashWelcomeTitle = document.getElementById("dashWelcomeTitle"); if (dashWelcomeTitle) dashWelcomeTitle.textContent = t('dashWelcomeTitle');
  const dashDesc = document.getElementById("dashDesc"); if (dashDesc) dashDesc.textContent = t('dashDesc');
  const dashStartBtn = document.getElementById("dashStartBtn"); if (dashStartBtn) dashStartBtn.textContent = t('dashStartBtn');
  const dashPlayerTitle = document.getElementById("dashPlayerTitle"); if (dashPlayerTitle) dashPlayerTitle.textContent = t('dashPlayerTitle');
  const dashPlayerDesc = document.getElementById("dashPlayerDesc"); if (dashPlayerDesc) dashPlayerDesc.textContent = t('dashPlayerDesc');

  const panelStatsHeader = document.getElementById("panelStatsHeader"); if (panelStatsHeader) panelStatsHeader.textContent = t('panelStatsHeader');
  const labelWhiteWins = document.getElementById("labelWhiteWins"); if (labelWhiteWins) labelWhiteWins.textContent = t('labelWhiteWins');
  const labelBlackWins = document.getElementById("labelBlackWins"); if (labelBlackWins) labelBlackWins.textContent = t('labelBlackWins');
  const labelDraws = document.getElementById("labelDraws"); if (labelDraws) labelDraws.textContent = t('labelDraws');
  const btnResetStats = document.getElementById("btnResetStats"); if (btnResetStats) btnResetStats.textContent = t('btnResetStats');
  const btnNewGame = document.getElementById("btnNewGame"); if (btnNewGame) btnNewGame.textContent = t('btnNewGame');
  const btnResign = document.getElementById("btnResign"); if (btnResign) btnResign.textContent = t('btnResign');
  const panelHistoryHeader = document.getElementById("panelHistoryHeader"); if (panelHistoryHeader) panelHistoryHeader.textContent = t('panelHistoryHeader');

  const loginCardTitle = document.getElementById("loginCardTitle"); if (loginCardTitle) loginCardTitle.textContent = t('loginCardTitle');
  const labelLoginUsername = document.getElementById("labelLoginUsername"); if (labelLoginUsername) labelLoginUsername.textContent = t('labelLoginUsername');
  const labelLoginPassword = document.getElementById("labelLoginPassword"); if (labelLoginPassword) labelLoginPassword.textContent = t('labelLoginPassword');
  const btnLoginSubmit = document.getElementById("btnLoginSubmit"); if (btnLoginSubmit) btnLoginSubmit.textContent = t('btnLoginSubmit');
  const noAccountText = document.getElementById("noAccountText"); if (noAccountText) noAccountText.textContent = t('noAccountText');
  const goToRegisterLink = document.getElementById("goToRegisterLink"); if (goToRegisterLink) goToRegisterLink.textContent = t('goToRegisterLink');

  const regCardTitle = document.getElementById("regCardTitle"); if (regCardTitle) regCardTitle.textContent = t('regCardTitle');
  const labelRegUsername = document.getElementById("labelRegUsername"); if (labelRegUsername) labelRegUsername.textContent = t('labelRegUsername');
  const labelRegEmail = document.getElementById("labelRegEmail"); if (labelRegEmail) labelRegEmail.textContent = t('labelRegEmail');
  const labelRegPassword = document.getElementById("labelRegPassword"); if (labelRegPassword) labelRegPassword.textContent = t('labelRegPassword');
  const btnRegSubmit = document.getElementById("btnRegSubmit"); if (btnRegSubmit) btnRegSubmit.textContent = t('btnRegSubmit');
  const hasAccountText = document.getElementById("hasAccountText"); if (hasAccountText) hasAccountText.textContent = t('hasAccountText');
  const goToLoginLink = document.getElementById("goToLoginLink"); if (goToLoginLink) goToLoginLink.textContent = t('goToLoginLink');

  const profileCardTitle = document.getElementById("profileCardTitle"); if (profileCardTitle) profileCardTitle.textContent = t('profileCardTitle');
  const profLabelWins = document.getElementById("profLabelWins"); if (profLabelWins) profLabelWins.textContent = t('profLabelWins');
  const profLabelLosses = document.getElementById("profLabelLosses"); if (profLabelLosses) profLabelLosses.textContent = t('profLabelLosses');
  const profLabelDraws = document.getElementById("profLabelDraws"); if (profLabelDraws) profLabelDraws.textContent = t('profLabelDraws');
  const profLabelRating = document.getElementById("profLabelRating"); if (profLabelRating) profLabelRating.textContent = t('profLabelRating');
  const btnLogout = document.getElementById("btnLogout"); if (btnLogout) btnLogout.textContent = t('btnLogout');

  // Profil modal oynasi
  const profFideIdLabel = document.getElementById("profFideIdLabel"); if (profFideIdLabel) profFideIdLabel.textContent = t('profFideIdLabel');
  const profGoalLabel = document.getElementById("profGoalLabel"); if (profGoalLabel) profGoalLabel.textContent = t('profGoalLabel');
  const copyProfileLinkBtn = document.getElementById("copyProfileLinkBtn"); if (copyProfileLinkBtn) copyProfileLinkBtn.textContent = '🔗 ' + t('profCopyLinkBtn');
  const logoutProfileBtn = document.getElementById("logoutProfileBtn"); if (logoutProfileBtn) logoutProfileBtn.textContent = '🚪 ' + t('btnLogout');
  const profRatingsTab = document.getElementById("profRatingsTab"); if (profRatingsTab) profRatingsTab.textContent = '📊 ' + t('profRatingsBtn');
  const editProfileBtn = document.getElementById("editProfileBtn"); if (editProfileBtn) editProfileBtn.textContent = '✏️ ' + t('profEditBtn');
  const saveProfileBtn = document.getElementById("saveProfileBtn"); if (saveProfileBtn) saveProfileBtn.textContent = '💾 ' + t('profSaveBtn');
  const profStatRapidTitle = document.getElementById("profStatRapidTitle"); if (profStatRapidTitle) profStatRapidTitle.textContent = t('profRapidRating');
  const profStatBlitzTitle = document.getElementById("profStatBlitzTitle"); if (profStatBlitzTitle) profStatBlitzTitle.textContent = t('profBlitzRating');
  const profStatBulletTitle = document.getElementById("profStatBulletTitle"); if (profStatBulletTitle) profStatBulletTitle.textContent = t('profBulletRating');
  const profStatDebutTitle = document.getElementById("profStatDebutTitle"); if (profStatDebutTitle) profStatDebutTitle.textContent = t('profBestOpening');
  const profStatClubTitle = document.getElementById("profStatClubTitle"); if (profStatClubTitle) profStatClubTitle.textContent = t('profClubLabel');
  const profStatStatusTitle = document.getElementById("profStatStatusTitle"); if (profStatStatusTitle) profStatStatusTitle.textContent = t('profStatusLabel');
  const profStatusActive = document.getElementById("profStatusActive"); if (profStatusActive) profStatusActive.textContent = t('profStatusActive');

  const leaderboardCardTitle = document.getElementById("leaderboardCardTitle"); if (leaderboardCardTitle) leaderboardCardTitle.textContent = t('leaderboardTitle');
  const leaderboardDesc = document.getElementById("leaderboardDesc"); if (leaderboardDesc) leaderboardDesc.textContent = t('leaderboardDesc');
  const historyCardTitle = document.getElementById("historyCardTitle"); if (historyCardTitle) historyCardTitle.textContent = t('historyTitle');
  const historyDesc = document.getElementById("historyDesc"); if (historyDesc) historyDesc.textContent = t('historyDesc');

  const tournamentsCardTitle = document.getElementById("tournamentsCardTitle"); if (tournamentsCardTitle) tournamentsCardTitle.textContent = t('tournamentsTitle');
  const tournamentsDesc = document.getElementById("tournamentsDesc"); if (tournamentsDesc) tournamentsDesc.textContent = t('tournamentsDesc');

  const clubsCardTitle = document.getElementById("clubsCardTitle"); if (clubsCardTitle) clubsCardTitle.textContent = t('clubsTitle');
  const clubsDesc = document.getElementById("clubsDesc"); if (clubsDesc) clubsDesc.textContent = t('clubsDesc');
  const btnCreateClub = document.getElementById("btnCreateClub"); if (btnCreateClub) btnCreateClub.textContent = t('btnCreateClub');

  const chatCardTitle = document.getElementById("chatCardTitle"); if (chatCardTitle) chatCardTitle.textContent = t('chatTitle');
  const chatDesc = document.getElementById("chatDesc"); if (chatDesc) chatDesc.textContent = t('chatDesc');
  const btnSendChatMessage = document.getElementById("btnSendChatMessage"); if (btnSendChatMessage) btnSendChatMessage.textContent = t('btnSendChatMessage');

  const playOnlineBtn = document.getElementById("playOnlineBtn"); if (playOnlineBtn) playOnlineBtn.textContent = t('playOnlineBtn');
  const tabPlayers = document.getElementById("playersTab"); if (tabPlayers) tabPlayers.textContent = t('tabPlayers');
  const tabClubs = document.getElementById("clubsTab"); if (tabClubs) tabClubs.textContent = t('tabClubs');
  const searchCountry = document.getElementById("clubSearchInput"); if (searchCountry) searchCountry.placeholder = t('searchCountry');
  const filterAll = document.getElementById("filterAll"); if (filterAll) filterAll.textContent = t('filterAll');
  const filterRapid = document.getElementById("filterRapid"); if (filterRapid) filterRapid.textContent = t('filterRapid');
  const filterBlitz = document.getElementById("filterBlitz"); if (filterBlitz) filterBlitz.textContent = t('filterBlitz');
  const filterBullet = document.getElementById("filterBullet"); if (filterBullet) filterBullet.textContent = t('filterBullet');
  const colUsername = document.getElementById("colUsername"); if (colUsername) colUsername.textContent = t('colUsername');
  const colRating = document.getElementById("colRating"); if (colRating) colRating.textContent = t('colRating');
  const colWinPoints = document.getElementById("colWinPoints"); if (colWinPoints) colWinPoints.textContent = t('colWinPoints');
  const colWins = document.getElementById("colWins"); if (colWins) colWins.textContent = t('colWins');
  const colGames = document.getElementById("colGames"); if (colGames) colGames.textContent = t('colGames');
  const colWinPercent = document.getElementById("colWinPercent"); if (colWinPercent) colWinPercent.textContent = t('colWinPercent');
  const colPlayer = document.getElementById("colPlayer"); if (colPlayer) colPlayer.textContent = t('colPlayer');

  const mLeagues = document.getElementById("mLeagues"); if (mLeagues) mLeagues.textContent = t('mLeagues');
  const mChampions = document.getElementById("mChampions"); if (mChampions) mChampions.textContent = t('mChampions');
  const mSettings = document.getElementById("mSettings"); if (mSettings) mSettings.textContent = t('mSettings');
  const waitingSearching = document.getElementById("waitingSearching"); if (waitingSearching) waitingSearching.textContent = t('waitingSearching');
  const waitingPlease = document.getElementById("waitingPlease"); if (waitingPlease) waitingPlease.textContent = t('waitingPlease');
  const historyPanelHeader = document.getElementById("historyPanelHeader"); if (historyPanelHeader) historyPanelHeader.textContent = t('historyPanelHeader');
  const ratedLabel = document.getElementById("ratedLabel"); if (ratedLabel) ratedLabel.textContent = t('ratedLabel');
  const ratedSublabel = document.getElementById("ratedSublabel"); if (ratedSublabel) ratedSublabel.textContent = t('ratedSublabel');
  const btnDrawText = document.getElementById("btnDrawText"); if (btnDrawText) btnDrawText.textContent = t('btnDrawText');
  const btnResignText = document.getElementById("btnResignText"); if (btnResignText) btnResignText.textContent = t('btnResign');
  const btnPgnText = document.getElementById("btnPgnText"); if (btnPgnText) btnPgnText.textContent = t('btnPgnText');
  const btnStartGameText = document.getElementById("btnStartGameText"); if (btnStartGameText) btnStartGameText.textContent = t('btnStartGameText');
  const timerLabelJudaTez = document.getElementById("timerLabelJudaTez"); if (timerLabelJudaTez) timerLabelJudaTez.textContent = t('timerLabelJudaTez');
  const timerLabelBlits = document.getElementById("timerLabelBlits"); if (timerLabelBlits) timerLabelBlits.textContent = t('timerLabelBlits');
  const timerLabelTezkor = document.getElementById("timerLabelTezkor"); if (timerLabelTezkor) timerLabelTezkor.textContent = t('timerLabelTezkor');

  const historyAllText = document.getElementById("historyAllText"); if (historyAllText) historyAllText.textContent = t('historyAllText');
  const historyWinsText = document.getElementById("historyWinsText"); if (historyWinsText) historyWinsText.textContent = t('historyWinsText');
  const historyLossesText = document.getElementById("historyLossesText"); if (historyLossesText) historyLossesText.textContent = t('historyLossesText');
  const historyDrawsText = document.getElementById("historyDrawsText"); if (historyDrawsText) historyDrawsText.textContent = t('historyDrawsText');
  const colDate = document.getElementById("colDate"); if (colDate) colDate.textContent = t('colDate');
  const colOpponent = document.getElementById("colOpponent"); if (colOpponent) colOpponent.textContent = t('colOpponent');
  const colMode = document.getElementById("colMode"); if (colMode) colMode.textContent = t('colMode');
  const colTime = document.getElementById("colTime"); if (colTime) colTime.textContent = t('colTime');
  const colResult = document.getElementById("colResult"); if (colResult) colResult.textContent = t('colResult');
  const leaguesDesc = document.getElementById("leaguesDesc"); if (leaguesDesc) leaguesDesc.textContent = t('leaguesDesc');
  const leagueAsia = document.getElementById("leagueAsia"); if (leagueAsia) leagueAsia.textContent = t('leagueAsia');
  const leagueEurope = document.getElementById("leagueEurope"); if (leagueEurope) leagueEurope.textContent = t('leagueEurope');
  const leagueAfrica = document.getElementById("leagueAfrica"); if (leagueAfrica) leagueAfrica.textContent = t('leagueAfrica');
  const leagueSouthAmerica = document.getElementById("leagueSouthAmerica"); if (leagueSouthAmerica) leagueSouthAmerica.textContent = t('leagueSouthAmerica');
  const leagueNorthAmerica = document.getElementById("leagueNorthAmerica"); if (leagueNorthAmerica) leagueNorthAmerica.textContent = t('leagueNorthAmerica');
  const leagueOceania = document.getElementById("leagueOceania"); if (leagueOceania) leagueOceania.textContent = t('leagueOceania');
  const championWinnerAsia = document.getElementById("championWinnerAsia"); if (championWinnerAsia) championWinnerAsia.textContent = t('championWinnerLabel');
  const championWinnerEurope = document.getElementById("championWinnerEurope"); if (championWinnerEurope) championWinnerEurope.textContent = t('championWinnerLabel');
  const championWinnerAfrica = document.getElementById("championWinnerAfrica"); if (championWinnerAfrica) championWinnerAfrica.textContent = t('championWinnerLabel');
  const championWinnerSouthAmerica = document.getElementById("championWinnerSouthAmerica"); if (championWinnerSouthAmerica) championWinnerSouthAmerica.textContent = t('championWinnerLabel');
  const championWinnerNorthAmerica = document.getElementById("championWinnerNorthAmerica"); if (championWinnerNorthAmerica) championWinnerNorthAmerica.textContent = t('championWinnerLabel');
  const championWinnerOceania = document.getElementById("championWinnerOceania"); if (championWinnerOceania) championWinnerOceania.textContent = t('championWinnerLabel');
  const championsTitle = document.getElementById("championsTitle"); if (championsTitle) championsTitle.textContent = t('championsTitle');
  const championsSubtitle = document.getElementById("championsSubtitle"); if (championsSubtitle) championsSubtitle.textContent = t('championsSubtitle');
  const tournamentFormatTitle = document.getElementById("tournamentFormatTitle"); if (tournamentFormatTitle) tournamentFormatTitle.textContent = t('tournamentFormatTitle');
  const roundRobinRule1 = document.getElementById("roundRobinRule1"); if (roundRobinRule1) roundRobinRule1.textContent = t('roundRobinRule1');
  const roundRobinRule2 = document.getElementById("roundRobinRule2"); if (roundRobinRule2) roundRobinRule2.textContent = t('roundRobinRule2');
  const roundRobinRule3 = document.getElementById("roundRobinRule3"); if (roundRobinRule3) roundRobinRule3.textContent = t('roundRobinRule3');
  const roundRobinRule4 = document.getElementById("roundRobinRule4"); if (roundRobinRule4) roundRobinRule4.textContent = t('roundRobinRule4');

  const settingsTitle = document.getElementById("settingsTitle"); if (settingsTitle) settingsTitle.textContent = t('settingsTitle');
  const settingsSubtitle = document.getElementById("settingsSubtitle"); if (settingsSubtitle) settingsSubtitle.textContent = t('settingsSubtitle');
  const settingsCountryTitle = document.getElementById("settingsCountryTitle"); if (settingsCountryTitle) settingsCountryTitle.textContent = t('settingsCountryTitle');
  const settingsCountryLabel = document.getElementById("settingsCountryLabel"); if (settingsCountryLabel) settingsCountryLabel.textContent = t('settingsCountryLabel');
  const settingsLanguageTitle = document.getElementById("settingsLanguageTitle"); if (settingsLanguageTitle) settingsLanguageTitle.textContent = t('settingsLanguageTitle');
  const settingsLanguageLabel = document.getElementById("settingsLanguageLabel"); if (settingsLanguageLabel) settingsLanguageLabel.textContent = t('settingsLanguageLabel');
  const settingsSoundTitle = document.getElementById("settingsSoundTitle"); if (settingsSoundTitle) settingsSoundTitle.textContent = t('settingsSoundTitle');
  const settingsSoundLabel = document.getElementById("settingsSoundLabel"); if (settingsSoundLabel) settingsSoundLabel.textContent = t('settingsSoundLabel');
  const settingsVolumeLabel = document.getElementById("settingsVolumeLabel"); if (settingsVolumeLabel) settingsVolumeLabel.textContent = t('settingsVolumeLabel');
  const settingsDesignTitle = document.getElementById("settingsDesignTitle"); if (settingsDesignTitle) settingsDesignTitle.textContent = t('settingsDesignTitle');
  const settingsThemeLabel = document.getElementById("settingsThemeLabel"); if (settingsThemeLabel) settingsThemeLabel.textContent = t('settingsThemeLabel');
  const settingsCoordsLabel = document.getElementById("settingsCoordsLabel"); if (settingsCoordsLabel) settingsCoordsLabel.textContent = t('settingsCoordsLabel');
  const settingsSaveBtn = document.getElementById("settingsSaveBtn"); if (settingsSaveBtn) settingsSaveBtn.textContent = t('settingsSaveBtn');
  const settingsResetBtn = document.getElementById("settingsResetBtn"); if (settingsResetBtn) settingsResetBtn.textContent = t('settingsResetBtn');

  const continentTabAll = document.getElementById("continentTabAll"); if (continentTabAll) continentTabAll.textContent = t('continentAll');
  const continentTabAsia = document.getElementById("continentTabAsia"); if (continentTabAsia) continentTabAsia.textContent = t('continentAsia');
  const continentTabEurope = document.getElementById("continentTabEurope"); if (continentTabEurope) continentTabEurope.textContent = t('continentEurope');
  const continentTabAfrica = document.getElementById("continentTabAfrica"); if (continentTabAfrica) continentTabAfrica.textContent = t('continentAfrica');
  const continentTabSouthAmerica = document.getElementById("continentTabSouthAmerica"); if (continentTabSouthAmerica) continentTabSouthAmerica.textContent = t('continentSouthAmerica');
  const continentTabNorthAmerica = document.getElementById("continentTabNorthAmerica"); if (continentTabNorthAmerica) continentTabNorthAmerica.textContent = t('continentNorthAmerica');
  const continentTabOceania = document.getElementById("continentTabOceania"); if (continentTabOceania) continentTabOceania.textContent = t('continentOceania');

  // Agar Klublar sahifasi ochiq bo'lsa, ro'yxatni qayta chizish
  const clubsView = document.getElementById('clubsView');
  if (clubsView && clubsView.classList.contains('active-view')) {
    if (typeof window.loadClubs === 'function') window.loadClubs();
  }

  // Agar Ligalar sahifasi ochiq bo'lsa, kartalarni qayta chizish
  const leaguesView = document.getElementById('leaguesView');
  if (leaguesView && leaguesView.classList.contains('active-view')) {
    if (typeof window.renderLeagues === 'function') window.renderLeagues();
  }

  const dashClubsBtn = document.getElementById("dashClubsBtn"); if (dashClubsBtn) dashClubsBtn.textContent = t('clubsTitle');

  if (typeof window.updateTopPlayersList === 'function') window.updateTopPlayersList();

  if (typeof window.updateAuthHeaderUI === 'function') window.updateAuthHeaderUI();
  if (typeof window.updateStreakUI === 'function') window.updateStreakUI();
  if (typeof window.updateTimersDisplay === 'function') window.updateTimersDisplay();
}

window.setLanguage = function(lang) {
  currentLang = lang;
  localStorage.setItem("justChessLang", lang);
  i18next.changeLanguage(lang, () => {
    updateUI();
  });
};

window.changeLanguage = function(lang) {
  window.setLanguage(lang);
};
